### ISSUE TITLE
Allow Range header to work with Google Cloud Storage

### ISSUE THREAD

**Issue by tronathan** [fog/fog-google#107]
The gem seems to support the http `Range:` header in requests, however it doesn't accept the `206` response from google, which is required. (206 = Partial Content)

The following PR adds basic support for accepting `206 Partial Content`, allowing the `Range` header to be used to get objects from GCS:

https://github.com/fog/fog-google/pull/106

**Comment by icco** [comment]
I'm reviewing the PR (no need to open both a PR and an Issue).
