### ISSUE TITLE
We should release 0.2.0 with new Storage API

### ISSUE THREAD

**Issue by icco** [fog/fog-google#109]
@Temikus @plribeiro3000 Thoughts?

**Comment by plribeiro3000** [comment]
Are we breaking the old api? If not i don't see a problem.

**Comment by icco** [comment]
No, just a large refactor of the storage code with new features.

https://github.com/fog/fog-google/pull/100 should probably get merged after it's out (although I need to work on that PR more).

**Comment by icco** [comment]
I'll wait for @Temikus and https://github.com/fog/fog-google/pull/105 and https://github.com/fog/fog-google/pull/106 to get merged, and then I'll pop out 0.2.0.

**Comment by Temikus** [comment]
@icco SGTM :+1:

**Comment by icco** [comment]
Done!
