### ISSUE TITLE
Remove get_object_torrent request

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#125]
Either it was silently deprecated or nobody noticed that it doesn't exist for a surprising amount of time.
Calling `torrent` parameter results in `invalid_request`.

XML API doesn't specify a torrent parameter:
https://cloud.google.com/storage/docs/xml-api/reference-headers#query-string-parameters

If it wasn't deprecated I have a feeling that we may have just copied AWS code and cargo-culted it until now: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGETtorrent.html

/CC @icco @plribeiro3000 - do you guys know whether we actually need this method?

**Comment by plribeiro3000** [comment]
Dunno. It might be a bad copy and paste. Give me some time to look over `fog` to check when it was inserted.

**Comment by plribeiro3000** [comment]
So [here](https://github.com/fog/fog/blob/c596e710952aa9c90713da3fbfb3027db0608413/lib/fog/google/requests/storage/get_object_torrent.rb) is the original file and it was inserted on fog/fog@bdd2ca309458e7f2049812c50ad4f8fec3c0e543 so it was indeed a bad copy and paste.

**Comment by icco** [comment]
So iirc, I stopped testing the torrent feature because google doesn't support it. I thought I removed it from code...

**Comment by icco** [comment]
(can't find any mention of torrent in their docs, but haven't tested, this is just from my memory)

**Comment by Temikus** [comment]
@icco No worries, thanks for the update!
Funny how we cargo-culted it for 6 years :)

@plribeiro3000 Should I rip it out or do you want to?

**Comment by plribeiro3000** [comment]
Go for it. I'm kind of without time today.

**Comment by Temikus** [comment]
@plribeiro3000 Ack, I'll do it this week.

**Comment by Temikus** [comment]
Fixed by #129
