### ISSUE TITLE
Obsolete development dependencies

### ISSUE THREAD

**Issue by ihmccreery** [fog/fog-google#13]
Currently, `fog-google.gemspec` says that `fog-google` relies on `pry`, `vcr`, `webmock`, `coveralls`, and `rubocop` as development dependencies.  Should some of these be removed?

**Comment by plribeiro3000** [comment]
@ihmccreery When migrating i've added some options that could be removed as you guys wanted.

For a better explaining see: https://github.com/fog/fog-google/issues/3#issuecomment-89003369

`rubocop` it a must have. All the providers should follow the conventions we have in fog which is/should be the `github` style guide.
`webmock`, `vcr` and `pry` are pretty good. They do a pretty good job as tools to help testing but as i mentioned before, this is up to you to choose if you want to keep or remove them.

**Comment by ihmccreery** [comment]
@plribeiro3000 Great, thanks for the clarification.  This probably (again) moves into documentation-land.  If the `fog` community is expected to maintain `rubocop` compliance, we should note that in CONTRIBUTING.  I currently see >8,000 violations in this codebase.  Opened issue #15 with low priority.

I'm going to keep this issue open for `webmock`, `vcr`, and `pry` and marked for v0.1.0.  Let's reconsider this once all of the tests are passing and we've moved to `minitest`.  While they might be good, if our codebase doesn't depend on them, they probably shouldn't be dependencies.

**Comment by plribeiro3000** [comment]
Sure thing. =)

**Comment by Temikus** [comment]
Ok, so, I propose:
- Everything not required for any rake task goes into `Gemfile` `:development` group.
- Everything else stays in `gemspec`

So, `vcr`, `webmock`, `coveralls`, and `rubocop` should stay in development deps and pry either added to a `rake console` task or moved to Gemfile.

@plribeiro3000 WDYT?

**Comment by plribeiro3000** [comment]
Just google `WDYT`. ahhahah

Dunno man, is it a problem to have those dependencies as development dependencies?

If not i would think is better to keep it in `gemspec` since is the first place people go to see the dependencies but is not a hard feeling.

**Comment by Temikus** [comment]
@plribeiro3000 Thanks for your thoughts! I don't think that having a debugger and necessary development dependencies is bad. They don't get installed in the runtime anyway.

Closing.
