### ISSUE TITLE
Activesupport/google-api-clien dependency issues

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#138]
It seems that currently all builds before ruby `2.2.2` are failing due to activesupport `5.0.0`:

@selmanj - Looking at this diagonally this seems to be a `google-api-client` problem, changed when you added pubsub in #118 

Previous versions (before 0.8.5) used to have a proper pessimistic constraint on activesupport: https://rubygems.org/gems/google-api-client/versions/0.8.4

Can you tell me which version does your pubsub implementation rely on? Is it ok to roll back to 0.8.4?

**Comment by selmanj** [comment]
It's unfortunately not ok; 0.8.6 is required for pubsub to work properly; previous versions parsed the discovery doc for pubsub incorrectly.

For now I'll send a PR fixing activesupport to an older version. I think the real fix is to move to google-api 0.9 (where this dependency is now removed).

**Comment by Temikus** [comment]
ActiveSupport is not needed in there in the first place. It was used to basically camelcase/decamelcase a string... https://github.com/google/google-api-ruby-client/issues/364

@selmanj Ack. Thanks!
