### ISSUE TITLE
Storage JSON request names

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#147]
I noticed that all of our requests try to mirror old XML API names. As in (`put` vs `insert`).
Should I think about renaming the requests properly to correspond to method names in the next version and create deprecation stubs?

Otherwise it seems that we'll have issues going forward since JSON API has different method structure on Google's side.

@icco @plribeiro3000 - Thoughts?

**Comment by icco** [comment]
Hmm, most of it was done originally so we didn't have to change any of the models.

**Comment by Temikus** [comment]
Understood, I'll think about carefully refactoring this.

**Comment by plribeiro3000** [comment]
@Temikus Dunno. Can you give me a sample?

**Comment by Temikus** [comment]
@plribeiro3000 
lib/fog/storage/google_json/requests/put_bucket.rb
```
 api_method = @storage_json.buckets.insert
```
, so, it calls the insert_bucket RPC method, however, the method and request themselves are called "put_bucket". Since this is not how API is structured, as we add more features I feel we're going to run into inconsistencies :/

**Comment by plribeiro3000** [comment]
Gotcha. Makes sense to rename then i guess.

**Comment by icco** [comment]
FYI, this won't be quite as applicable once https://github.com/fog/fog-google/pull/210 is done, as it will be removing the whole api_method thing.

**Comment by Temikus** [comment]
@icco Good to know, thanks!

**Comment by icco** [comment]
This has been mostly solved with 1.0.0 I believe. I'm going to close for now.
