### ISSUE TITLE
Comply with Ruby styleguides per Rubocop

### ISSUE THREAD

**Issue by ihmccreery** [fog/fog-google#15]
```
$ rubocop
[...]
388 files inspected, 8160 offenses detected
```

**Comment by ihmccreery** [comment]
@Temikus recommends incorporating this into Travis on #47.  +1.

**Comment by plribeiro3000** [comment]
:+1:

**Comment by Temikus** [comment]
I recently introduced linters into another project, so quickly made a foundation for fog-google.

**Comment by Temikus** [comment]
This was incorporated into our CI in #89 and the number of violations severely cut:
```
484 files inspected, 275 offenses detected
```
We may want to do some digging to lower this further, however, since Rubocop is opinionated, we shouldn't be shy on changing the Cops or disabling the linter in code where truly necessary, as in:
```
    module Action # rubocop:disable Metrics/ModuleLength
```

**Comment by icco** [comment]
Yeah, I think we're making decent progress on this. Going to close this ticket.
