### ISSUE TITLE
Unable to specify proxy option when using any google client

### ISSUE THREAD

**Issue by selmanj** [fog/fog-google#153]
The base google-api-client supports specifying a proxy option:

https://github.com/google/google-api-ruby-client/blob/v0.8.6/lib/google/api_client.rb#L110

fog-google just needs to be extended to expose it. Should be pretty easy to add.

**Comment by Temikus** [comment]
Wait, it already does support proxy by grabbing the `http_proxy` variable from the environment. 
This is IMO a correct way to set those settings since prod proxies usually require some sort of credentials.

**Comment by selmanj** [comment]
Is that the correct way?  How are the credentials set?

I believe the other fog providers handle the proxy option via the options array; an environment variable works but tends to be a lot less explicit.

**Comment by Temikus** [comment]
@selmanj Already discussed in the #154 - they want to add a provider-specific proxy option, so this will not do indeed.

P.S. On how credentials are set usually:
```
export http_proxy='http://user:password@prox-server:3128'
export https_proxy='http://user:password@prox-server:3128'
export ftp_proxy='http://user:password@prox-server:3128'
```

**Comment by selmanj** [comment]
@Temikus I don't think the proxy option is provider-specific; the AWS one for example accepts proxy. Adding the ability to specify the proxy in the options allows different proxy settings for different services, and tends to be more explicit than relying on environment variables.

I can't tell where you guys landed on #154 regarding this option, but I strongly feel that relying on just the environment variable is both hard-to-discover for users, and brittle.

**Comment by Temikus** [comment]
@selmanj As I said in #154, I think yours is a good idea and I like that type of implementation since we won't need to provide a proxy option (next google-api-client may very well not support it, for example)

**Comment by kgaikwad** [comment]
@Temikus, I would like to know what is pending for this change.

**Comment by kgaikwad** [comment]
> Any suggestions on this?
Please ignore. Got the reference - https://github.com/fog/fog-google/pull/418#issuecomment-422848146
