### ISSUE TITLE
Release 0.4

### ISSUE THREAD

**Issue by icco** [fog/fog-google#157]
A new version was requested in https://github.com/fog/fog-google/pull/156.

https://github.com/fog/fog-google/compare/v0.3.2...9f993717bf0a3654d8f002d941aa451aca5b7100

These changes seem to be pretty small, but there are a few function name changes, so I'm going to do a minor version bump. I'll start this now.

cc @Temikus & @plribeiro3000 & @erjohnso

**Comment by icco** [comment]
Done.

 - https://rubygems.org/gems/fog-google/versions/0.4.0
 - https://github.com/fog/fog-google/releases/tag/v0.4.0

**Comment by erjohnso** [comment]
@icco - you rock sir!  Thank you!

**Comment by dsboulder** [comment]
Thank you, all!!!
