### ISSUE TITLE
rescue Fog::Errors::NotFound instead of Excon::Errors::NotFound

### ISSUE THREAD

**Issue by rjdegelder** [fog/fog-google#161]
Hi guys,
I've been using fog-google with carrierwave to store uploads on Google Storage. Seem like there is an issue with fetching files (and directories) when the file is missing upstream.

In lib/fog/google/shared.rb:181 a Fog::Error::NotFound is raised when a request returns 404 but in your models in lib/fog/storage you're rescuing Excon::Error::NotFound.
I guess this should be changed in Fog::Errors::NotFound, or am I missing something here?

**Comment by Temikus** [comment]
Thanks for submitting this! Sorry it took a bit of time to reply, slipped through the cracks.
Submitted a fix.

@rjdegelder do you have a code snippet or something of how you use CarrierWave so this gets reproduced? Want to make sure it's in our tests going forward.

**Comment by Temikus** [comment]
Fixed.
