### ISSUE TITLE
Fog::Compute::Google.get_target_pool_health doesn't allow you to specify an instance

### ISSUE THREAD

**Issue by selmanj** [fog/fog-google#162]
The current implementation found in `fog-google/lib/fog/compute/google/requests/get_target_pool_health.rb` loops over every instance in the target_pool and makes an API call. Unfortunately the GCP api throws an error if the instance no longer exists or isn't created yet, which bubbles up to the caller.

This means that if a single instance doesn't exist in a target pool or isn't ready, then the caller has no way to identify the state of any of the other resources in that target_pool.  A simple fix is to just take the instance as an extra parameter.

**Comment by Temikus** [comment]
Fixed by #177
