### ISSUE TITLE
servers::bootstrap should use disk/autoDelete

### ISSUE THREAD

**Issue by ihmccreery** [fog/fog-google#17]
Right now, bootstrapped servers automatically create a disk to use with the server, but do not automatically destroy that disk when the server is destroyed.  I propose we use the disk/autoDelete option when creating bootstrapped instances, to avoid orphaned disks, (more info [here](https://cloud.google.com/compute/docs/instances#startinstanceapi)).

@icco You know this codebase better than I do; objections?  Thanks.

**Comment by ihmccreery** [comment]
This is technically a breaking change, so I'm marking it for v1.0.0.

**Comment by icco** [comment]
Sure, that seems reasonable. When I wrote the code that option didn't exist.

**Comment by icco** [comment]
We can do this whenever.
