### ISSUE TITLE
servers.create() confusingly takes both fog style and Google style parameters

### ISSUE THREAD

**Issue by selmanj** [fog/fog-google#183]
In some cases it always prefers one over the other.

This is most apparent when provisioning a server with a static ip address. For example, if you try to provision a server via:
```ruby
    my_server = client.servers.create(
      :name => new_resource_name,
      :machine_type => "f1-micro",
      :zone_name => DEFAULT_ZONE,
      :disks => [
        :boot => true,
        :autoDelete => true,
        :initializeParams => {
          :sourceImage => "projects/debian-cloud/global/images/family/debian-8"
        }
      ],
      :networkInterfaces => [
        :accessConfigs => [
          :type => "ONE_TO_ONE_NAT",
          :name => "External NAT",
          :natIP => "#{my_address.address}"
        ]
      ]
    )
```
the `networkInterfaces` value is silently dropped. Instead, `insert_server` requires that you specify the address via `:external_ip`:

```ruby
    my_server = client.servers.create(
      :name => new_resource_name,
      :machine_type => "f1-micro",
      :zone_name => DEFAULT_ZONE,
      :disks => [
        :boot => true,
        :autoDelete => true,
        :initializeParams => {
          :sourceImage => "projects/debian-cloud/global/images/family/debian-8"
        }
      ],
      :external_ip => my_address.address
    )
```

I'm not sure if this is a bug or not specifically around external ip addresses, but it seems to me the long-term fix is to instead make two different apis: one for using fog-style parameters (probably still under the servers namespace) and one using google-style parameters.

**Comment by Temikus** [comment]
I think this is a relic from when there wasn't much Network settings in GCE.

I'm for just adding the possibility to configure networkInterfaces and map the `:external_ip` through a helper method using the proper notation.

@icco WDYT about this?

**Comment by icco** [comment]
Yeah, this is from back when their was only one type of network.

:+1: to : 

> I'm for just adding the possibility to configure networkInterfaces and map the :external_ip through a helper method using the proper notation.

external_ip is just a nice way of saying what we want, and that network interfaces is super confusing. We should always support the fog way of doing things as a nice interface to the GCE way of doing things.
