### ISSUE TITLE
Google Cloud Storage : signed URL from put_object_url generates InvalidPolicyDocument

### ISSUE THREAD

**Issue by RickCarlino** [fog/fog-google#195]
I currently use Google Cloud Storage with `paperclip` for image uploads. Everything works fine and my credentials are valid.

I now wish to generate a signed URL on Google Cloud Storage to give to users using Fog.

First I create a storage object:

    storage = Fog::Storage.new(
            provider: "Google",
            google_storage_access_key_id: "KNOWN_GOOD_ID",
            google_storage_secret_access_key: "KNOWN_GOOD_KEY")

Then I create the URL:

    storage.put_object_url("MY_BUCKET",
            "RANDOM_NAME.jpg",
            1.hour,
            'Content-Type' => 'image/jpeg')

Which return `https://storage.googleapis.com/MY_BUCKET/RANDOM_NAME.jpg?GoogleAccessId=REDACTED&Signature=REDACTED&Expires=3600`

In the past, if I temporarily enabled `AllUsers:W` (just temporarily!), I was able to POST a binary image (via Postman API client) to this bucket.

However, when I try to POST a jpeg file to the bucket using the signed URL I created above, I get this error:

    <?xml version='1.0' encoding='UTF-8'?>
    <Error>
        <Code>InvalidPolicyDocument</Code>
        <Message>The content of the form does not meet the conditions specified in the policy document.</Message>
        <Details>Missing policy</Details>
    </Error>

How do I resolve this `Missing policy` error? Did I forget a param?

**UPDATE:** I was able to create a URL via `gsutil` using `gsutil signurl -d 10m -m PUT key.json  gs://bucket/name.jpeg`, so perhaps it is not bad account config?

[original issue](https://github.com/fog/fog/issues/3938#issuecomment-272126806)

**Comment by selmanj** [comment]
From the GCP docs on the `policy` parameter:
```
*If you do not provide a security policy, requests are considered to be anonymous and will only work with buckets that have granted WRITE or FULL_CONTROL permission to anonymous users.
```

However you said above that you granted all users write privilege, so the POST should have succeeded.  Can you provide more details about what the ACL call looks like when you grant write permission to AllUsers?

**Comment by icco** [comment]
Closing due to lack of response.

**Comment by sudhanshuraheja** [comment]
It just means that one or more of the component that you had described during creating the signed URL does not match the request.

More details here - https://cloud.google.com/storage/docs/access-control/signed-urls

**Comment by olttwa** [comment]
@RickCarlino you don't need a policy to upload an image/object.
I too fell into that trap. Following the docs here: https://cloud.google.com/storage/docs/xml-api/put-object, I uploaded an image using following curl:

```
curl -v -X PUT https://storage.googleapis.com/your-bucket-name/path/to/filename\?Expires\=1541955144\&GoogleAccessId\=svc-acc-name%40gcp-project-name.iam.gserviceaccount.com\&Signature\=some-base64-encoded-signature -T /Users/local/path/to/filename
```

**Comment by olttwa** [comment]
If you've specified the `content-type` while generating the signed url, you'll have to provide the same as header in above request. Not to mention, the HTTP method should be same as when generating signed url.
