### ISSUE TITLE
Authorization via Application Default Credentials

### ISSUE THREAD

**Issue by aaronstillwell** [fog/fog-google#202]
Hi guys,

I've found no mention of authorizing fog-google via Application Default Credentials in the docs, and flicking through the source it looks as if passing a key manually is mandatory.

My use case is for Cloud Storage, for which one can apparently authenticate using Application Default Credentials when running in GCE. Google's own ruby cloud storage API apparently does this via a compute engine metadata service at runtime (see https://cloud.google.com/docs/authentication#getting_credentials_for_server-centric_flow).

Am I correct in understanding that this is not possible via fog-google at present?

If so I'll happily look to make a PR in the near future.

**Comment by icco** [comment]
I think you are correct. I haven't tested this usecase, but we are built ontop of google's ruby auth library. https://github.com/fog/fog-google/blob/master/lib/fog/google/shared.rb#L19-L69 is the code you would want to modify.

**Comment by spil-rolph** [comment]
FYI, I got it to work locally by commenting the following lines:
https://github.com/fog/fog-google/blob/6ca3d3362b97e6a43003de8e463bdb45ba4a9184/lib/fog/google/shared.rb#L91-L95

And by changing `::Google::Auth::ServiceAccountCredentials` to `::Google::Auth::DefaultCredentials` on this line:
https://github.com/fog/fog-google/blob/6ca3d3362b97e6a43003de8e463bdb45ba4a9184/lib/fog/google/shared.rb#L105

`::Google::Auth::DefaultCredentials.make_creds` takes care of loading the correct class based on the json supplied:
https://github.com/google/google-auth-library-ruby/blob/6f6b25ba1807cba9dc8f19fd5ffa1b94775e192e/lib/googleauth/default_credentials.rb#L48-L60

Only tested it locally, so mileage may vary ;)

**Comment by Temikus** [comment]
Should be fixed by #442 

But if I'm missing something - feel free to reopen!
