### ISSUE TITLE
JSON-API: `is_truncated` missing in Files

### ISSUE THREAD

**Issue by MarcelHB** [fog/fog-google#206]
Hello,

last week, when attempting to do some `all(prefix: "...") { ... }` operation on a `Fog::Storage::GoogleJSON::Files` collection of a given directory, to my surprise, I received a `NoMethodError` for `is_truncated`.

In [v0.5.2 of this file, line 31](https://github.com/fog/fog-google/blob/v0.5.2/lib/fog/storage/google_json/models/files.rb#L31) (and older ones), there is a check for `is_truncated`. Looking at the rest of the code here, there is no such thing - but when comparing it to the[ XML version](https://github.com/fog/fog-google/blob/v0.5.2/lib/fog/storage/google_xml/models/files.rb#L11), there is this attribute.

Unfortunately, I cannot promise to look deeper into the JSON protocol to set things correctly, and we took another approach to work around this. I tried injecting the attribute from outside once which eradicated the error but seemed to ignore my `prefix` setting so far, giving me the wrong items.

Please keep track of this error. Thank you.

**Comment by icco** [comment]
Oh that's a legit error. Looks like just a bug from when we migrated to the json API.
