### ISSUE TITLE
Google Monitoring API needs to be updated to v3

### ISSUE THREAD

**Issue by icco** [fog/fog-google#208]
v2beta2 is deprecated.

https://cloud.google.com/monitoring/v2beta2/

**Comment by icco** [comment]
This is covered in #210

**Comment by erjohnso** [comment]
@icco - looks like Google has started shutting this off.  How do you feel about a one-off fix vs blocking #210?

If you're cool with that, I've asked @emilymye to take a look too. Hopefully it's not too big and we could get this added with a new 0.5 gem cut?

**Comment by icco** [comment]
Seems reasonable, sorry about the delay on 210.

**Comment by erjohnso** [comment]
Seriously? *We're* sorry about the delay on 210!!!

Thanks Nat - I haven't looked to see if it's a big deal, or just a 'vN' to 'vN+1' change. Emily will look today.

**Comment by emilymye** [comment]
Part one: #249

**Comment by icco** [comment]
#250 added v3 to the upgrade branch. Thanks @emilymye !
