### ISSUE TITLE
Google Cloud Storage: Support Storage Classes

### ISSUE THREAD

**Issue by johnsonj** [fog/fog-google#220]
GCS supports [storage classes](https://cloud.google.com/storage/docs/storage-classes) which are a property on a storage object that dictates it's access performance and price. For example a rarely accessed backup may be stored with `coldline` storage class.

It'd be great if `put_object` passed through an option for `storageClass` and set it on a `Google::Apis::StorageV1::Object` ([property](https://github.com/google/google-api-ruby-client/blob/e3b8c800d649da00748d4605d847b342480ecc73/generated/google/apis/storage_v1/classes.rb#L997)) as part of the `insert_object` call. 

Blocked on #210

**Comment by vimutter** [comment]
Hi, @johnsonj 
It seems that it's already possible. https://github.com/fog/fog-google/blob/master/lib/fog/storage/google_json/requests/put_object.rb#L63

Are you suggesting improving documentation for `put_object` ?
