### ISSUE TITLE
buckets list access error

### ISSUE THREAD

**Issue by myjoytou** [fog/fog-google#223]
I have created one `service account` for my project in `Google Cloud Storage`. I have assigned `owner` role to that service account and downloaded the private key JSON file. When I am calling 
```ruby 
connection = Fog::Storage::Google.new({ google_project: 'some-project', google_client_email: 'image-storage-internal@some-project.iam.gserviceaccount.com', google_json_key_location: '~/some-project-c4faf3122227.json'})
```
I am not getting any error. But while executing
> connection.list_buckets

I am getting an error: `Fog::Errors::Error: Caller does not have storage.buckets.list access to Project 795255435023`. 
Is there any issue with `Fog::Google` or I am missing some configuration for accessing `buckets list`?

**Comment by icco** [comment]
@myjoytou what version of fog-google are you using?

**Comment by myjoytou** [comment]
fog-google (0.5.3)
google-api-client (0.8.6)

**Comment by icco** [comment]
Hmm, that call should just work. I did a test with a newly created key for myself and it worked. What I'm not sure about is `connection.directories` (the model level method that you should be calling) is timing out for me. Will keep digging

**Comment by myjoytou** [comment]
Would you please tell me what extra permission you gave to your service account or how you have configured Google Storage Service. 
Thanks

**Comment by icco** [comment]
@myjoytou I used the owner role as you said. I did it at the project level though, if that matters.

**Comment by myjoytou** [comment]
Thanks, I will try again with fresh service account.
