### ISSUE TITLE
Upgrade google-api-client to 0.15

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#226]
Documenting current efforts on Google API Client updates (https://github.com/fog/fog-google/pull/210)

- [x] compute - @DawidJanczak + @icco + @emilymye
- [x] dns - @icco 
- [x] monitoring - @DawidJanczak  
- [x] pubsub - @Everlag
- [x] sql - @emilymye 
- [x] storage (JSON) - @Everlag 

Let me know if I forgot anything.

Let's do this!

_Last updated: 2017-10-23 by @erjohnso - open tasks / assignees revised_

**Comment by Everlag** [comment]
@selmanj is handing pubsub and storage off to me. After that, I'll take a shot at compute.

**Comment by Temikus** [comment]
@Everlag ACK

**Comment by Everlag** [comment]
We can mark PubSub as done, please add me for Compute.

Given its size, I likely won't be able to finish it in my remaining internship time, 2 weeks after this week, so I'll prepare to hand off to someone who will be able to.

**Comment by Everlag** [comment]
Storage can also be marked as done.

**Comment by icco** [comment]
Sounds great @DawidJanczak !

**Comment by emilymye** [comment]
@DawidJanczak @icco I actually was looking into upgrading monitoring to v3 for #208

**Comment by icco** [comment]
@emilymye Monitoring has been fixed in the upgrade branch. The question @erjohnso is asking in #208 is to update the master branch, which uses an old version of google-api-client.

**Comment by btm** [comment]
Did someone pick up compute from @Everlag?

**Comment by icco** [comment]
@btm - @DawidJanczak is currently working on it.

**Comment by icco** [comment]
Biggest missing piece still is SQL I believe, if someone wants to take that. I know @Temikus and I are pretty strapped for time as of late.

**Comment by icco** [comment]
@emilymye might be best to start on SQL, he's made a lot of progress so far (most is committed), unless you're more interested in writing tests, which we still sorely need in most sections.

**Comment by emilymye** [comment]
@icco Cool, I'll get started on SQL. I'll probably also help out with writing Compute tests and seeing if we're missing any functionality once the current compute code is migrated

**Comment by DawidJanczak** [comment]
Thanks for the offer @emilymye! For now I think @icco is right in that it's better to work on stuff that hasn't been started on yet, but it is quite possible you'll be done with SQL and tests before I finish with Compute. Like you noticed, there is quite a lot of it. If that's the case do let us know and I'm sure we'll be able to split it somehow.

**Comment by emilymye** [comment]
Just for future reference, it looks like the list_resource_record_sets.rb DNS request wasn't been migrated. I can do it after the compute work is done, or someone else can take a look at it.

**Comment by icco** [comment]
Yeah, I need to go back through the DNS work, it had a bunch of issues. If you get the time, it'd be appreciated.

**Comment by icco** [comment]
@emilymye has closed out the last remaining issues. We're going to do a 1.0 release later this week, and I'll be merging #210 tomorrow (Jan 1).

**Comment by icco** [comment]
1.0 is out!

**Comment by erjohnso** [comment]
Great way to kick off 2018! Big community effort and thank you all!

**Comment by Temikus** [comment]
This is awesome 🙌 🚀 🎆
