### ISSUE TITLE
Fog::Storage::GoogleJSON::Mock not working

### ISSUE THREAD

**Issue by Paxa** [fog/fog-google#243]
I try to use it for testing:
```ruby
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)

require 'bundler/setup'
require 'fog/core'
require 'fog/google'

Fog.mock!

connection = Fog::Storage.new(
  provider: 'google',
  google_json_key_location: '',
  google_project: 123
)

connection.put_bucket("test")

connection.put_object("test", 'test', "test")

p Fog::Storage::GoogleJSON::Mock.data
```
And got error:
```
% ruby test/try_fog.rb
/Users/me/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/fog-google-69001eecad3c/lib/fog/storage/google_json/requests/put_bucket.rb:47:in `put_bucket': undefined local variable or method `data' for #<Fog::Storage::GoogleJSON::Mock:0x007fb79d65acf0> (NameError)
	from test/try_fog.rb:98:in `<main>'
```

Seems like some code not copied from [fog/storage/google_xml/mock.rb](https://github.com/fog/fog-google/blob/master/lib/fog/storage/google_xml/mock.rb) to [fog/storage/google_json/mock.rb](https://github.com/fog/fog-google/blob/master/lib/fog/storage/google_json/mock.rb)

With this monkey patch it works:
```ruby
class Fog::Storage::GoogleJSON::Mock
  def self.acls(type)
    Fog::Storage::GoogleXML::Mock.acls(type)
  end

  def self.reset
    Fog::Storage::GoogleXML::Mock.reset
  end

  def self.data
    Fog::Storage::GoogleXML::Mock.data
  end

  def data
    self.class.data[@google_storage_access_key_id]
  end
end
```

**Comment by icco** [comment]
We're ripping out a lot of the JSON mocks since many of them are incorrect. Post v1 (which should be out in the new year), we'll be looking for contributors to help us redo our mock code for our JSON APIs. So if you have opinions of what you're looking for, we'd appreciate your input.

**Comment by icco** [comment]
Closing issue. 1.0.0 is out, and we have no more mocks for json backed objects.
