### ISSUE TITLE
Create a new instance from snapshot

### ISSUE THREAD

**Issue by dare05** [fog/fog-google#251]
I've tried doing:

```
p disk = connection.snapshots.get('dns')
server = connection.servers.create({
                                       :name => "test-from-snapshot",
                                       :machine_type => "f1-micro",
                                       :zone_name => "us-central1-b",
                                       :disks => [disk]})
```
but I get an error. A snapshot is a disk like any other disk, and this option should be supported.

**Comment by icco** [comment]
What version of fog-google are you using? 

Also, from my understanding, a snapshot is not a disk, but you can use it as a source to create a new disk from: https://cloud.google.com/compute/docs/reference/latest/instances/insert & https://cloud.google.com/compute/docs/reference/latest/disks/insert

```ruby
  disk = connection.disks.create(
    :name => "snapshot-test",
    :size_gb => 10,
    :zone_name => "us-central1-f",
    :source_snapshot => connection.snapshots.get('dns')
  )
server = connection.servers.create({
                                       :name => "test-from-snapshot",
                                       :machine_type => "f1-micro",
                                       :zone_name => "us-central1-b",
                                       :disks => [disk]})
```

I'm on a phone, so can't verify this, but give the above a try.

**Comment by dare05** [comment]
I've researched this a bit more and Google does NOT recommend to use a snapshot to create a disk because of heavy bandwidth issues, instead, use an image. So you can close this.
