### ISSUE TITLE
How to specify project when creating object?

### ISSUE THREAD

**Issue by geemus** [fog/fog-google#268]
See: https://stackoverflow.com/questions/47519702/fog-google-storage-specify-project

I suspected it might be that they needed to put project under `fog_options` which would then be passed to the `directory.files.create(...)`. But looking at the put_object methods, I'm not finding clear reference to it.

@icco perhaps you know better than I? Thanks!

**Comment by icco** [comment]
Since they are using a access_key and secret pair (and by doing so using the Google Storage XML API), they do not need to specify a project, since access keys are tied to a project.

```
$ irb
2.4.0 :001 > require 'fog/google'
 => true
2.4.0 :002 >
2.4.0 :003 >   connection = Fog::Storage.new({
2.4.0 :004 >         provider:                         'Google',
2.4.0 :005 >         google_storage_access_key_id:     'MYKEYID',
2.4.0 :006 >         google_storage_secret_access_key: 'MYSECRET'
2.4.0 :007?>     })
 => #<Fog::Storage::GoogleXML::Real:70271319462720 @google_storage_access_key_id="MYKEYID" @google_storage_secret_access_key="MYSECRET" @connection_options={} @hmac=#<Fog::HMAC:0x007fd2a211a1a8 @key="MYSECRET", @digest=#<OpenSSL::Digest: da39a3ee5e6b4b0d3255bfef95601890afd80709>, @signer=#<Proc:0x007fd2a2119de8@/Users/natwelch/.rvm/gems/ruby-2.4.0/gems/fog-core-1.45.0/lib/fog/core/hmac.rb:21 (lambda)>> @host="storage.googleapis.com" @persistent=true @port=443 @scheme="https" @path_style=false>
```

**Comment by geemus** [comment]
@icco ah ha, cool, thanks for the clarification.

**Comment by icco** [comment]
Also checkout https://github.com/fog/fog-google/blob/master/lib/fog/storage/google.rb for the hack to deal with the fact that they have two storage APIs.
