### ISSUE TITLE
Invalid upload source when using Paperclip

### ISSUE THREAD

**Issue by sonicdoe** [fog/fog-google#289]
Using fog-google v1.0.0, I receive a `Google::Apis::ClientError (Invalid upload source)` error when uploading a file using [Paperclip](https://github.com/thoughtbot/paperclip). This seems to be a regression of https://github.com/fog/fog-google/pull/237.

In [`put_object.rb`](https://github.com/fog/fog-google/blob/2d4f0b2cd6d0f901121aafbc7146f4370cc7734c/lib/fog/storage/google_json/requests/put_object.rb#L49-L59), `data.path` will only be used if `data` responds to both `:content_type` and `:path` _and_ if `options[:content_type]` is falsy:

```rb
unless options[:content_type]
  if data.is_a?(String)
    data = StringIO.new(data)
    options[:content_type] = "text/plain"
  elsif data.is_a?(::File)
    options[:content_type] = Fog::Storage.parse_data(data)[:headers]["Content-Type"]
  elsif data.respond_to?(:content_type) && data.respond_to?(:path)
    options[:content_type] = data.content_type
    data = data.path
  end
end
```

Although this behavior hasn’t really changed in v1.0.0, `unless options["Content-Type"]` was changed to `unless options[:content_type]` in [`da9619b`](https://github.com/fog/fog-google/commit/da9619b34274e8112674e1ddced2392f1c5aa4f7#diff-639c71daef71f785b029dcb28455bbe8L21). Therefore, as far as I can tell, https://github.com/fog/fog-google/pull/237 only unintentionally worked because the option was actually passed as `contentType` instead of `Content-Type` (see [`da9619b`](https://github.com/fog/fog-google/commit/da9619b34274e8112674e1ddced2392f1c5aa4f7#diff-02a888ff0b756f121e1280a7935cb5d2L62)).

I’d suggest always using the `data`’s `path` and `content_type` if it responds to these methods by moving the if block out of the `unless options[:content_type]` block.

Note: I have only reproduced this in one Rails app at work and haven’t fully tested it in a fresh Rails app so far (which is also why I haven’t opened a pull request yet).

**Comment by icco** [comment]
@sonicdoe what you're saying seems reasonable. If you can find any other example of this failing (in a simple rails app or somewhere else), I think that'd be enough for me.

**Comment by icco** [comment]
Thanks for reporting and fixing @sonicdoe !
