### ISSUE TITLE
GoogleJSON directories#get does not accept a prefix option

### ISSUE THREAD

**Issue by tcdowney** [fog/fog-google#296]
In the older [GoogleXML implementation](https://github.com/fog/fog-google/blob/2d8da689c595cca6bf3bbca6f9382e6c2f4cc0e8/lib/fog/storage/google_xml/models/directories.rb#L21) you could pass this call a `prefix` option that would only fetch objects in the bucket that began with that prefix.

For example, this would only return objects directly under the `06824f8f-d185-409f-be75-55dba0a9a904` directory:
```
prefix = ' buildpack_cache/06/82/06824f8f-d185-409f-be75-55dba0a9a904'
connection.directories.get(dir.key, prefix: prefix).files
```

The newer API implementation no longer accepts `prefix`.
https://github.com/fog/fog-google/blob/2d8da689c595cca6bf3bbca6f9382e6c2f4cc0e8/lib/fog/storage/google_json/models/directories.rb#L12

Is there a way that support for the `prefix` option could be maintained?

Thanks!
Tim Downey && @maryamklabib

**Comment by icco** [comment]
I think the fact that worked before is a bug in the xml code. I would expect the call to be  

```ruby
connection.directories.get(dir.key).files(prefix: prefix)
```

For example the list call for files supports prefix in both APIs: https://cloud.google.com/storage/docs/json_api/v1/objects/list and https://cloud.google.com/storage/docs/xml-api/get-bucket-list

**Comment by tcdowney** [comment]
Hmm that's interesting. We'll test out calling it that way with `fog-aws` as well. Thanks!

**Comment by icco** [comment]
👍

**Comment by tcdowney** [comment]
@icco 

It actually looks like we can't pass any arguments to `directory#files`. When we do we're getting an `ArgumentError wrong number of arguments (given 1, expected 0)` here:

```
/stuff/fog-google-8beb64921385/lib/fog/storage/google_json/model
s/directory.rb:40:in `files'
```

https://github.com/fog/fog-google/blob/4647ce10acf171f74564b439cbce64676e4863e2/lib/fog/storage/google_json/models/directory.rb#L40-L47

The `fog-aws` implementation also doesn't support calling it this way.

**Comment by anniesing** [comment]
Thanks for re-opening the issue @erjohnso. Let us know if you need any other information that will help with debugging this issue. @elenasharma and I are taking this over from @tcdowney, so feel free to tag us directly as well.

Thanks,
Annie and Elena

**Comment by icco** [comment]
@anniesing I've merged in @emilymye's PR with a fix, please give it a try.

**Comment by maryamklabib** [comment]
@icco Thank you, everything seems to work great now. When will the next release be cut?

**Comment by icco** [comment]
I'll cut now, was just waiting for someone to verify :D

**Comment by erjohnso** [comment]
@icco 👏 👏 👏 👏 👏
