### ISSUE TITLE
Reconcile fog-google and fog/lib/fog/google

### ISSUE THREAD

**Issue by ihmccreery** [fog/fog-google#3]
Right now, `fog-google` and `fog/lib/fog/google` codebases don't reference each other.  `fog-google` is (kind of) under development, but fog doesn't pull those changes in.

We need to freeze one of these codebases to prevent having changes to both `fog-google` and `fog/lib/fog/google` that are difficult to merge.  I propose we either:

1. freeze `fog-google`, develop in `fog/lib/fog/google` to the point where we're confident that the code is not broken and properly tested, then pull that codebase into `fog-google`; or
2. freeze `fog/lib/fog/google`, pull it over to `fog-google`, (pretty much already done,) and *deprecate* `fog/lib/fog/google` so that all development is happening in `fog-google`.

I think the first option will be the easier one, and will have the highest probability of not exploding in our faces.  Transferring the whole codebase, where a lot of it is of unknown correctness, could be dangerous.  However, the first option goes back on the current trajectory, and also might mean that pulling that codebase into `fog-google` later will be more painful.

**Comment by ihmccreery** [comment]
@danbroudy @icco thoughts?

**Comment by icco** [comment]
The migration is an ongoing project led by @danbroudy. You're missing a completely valid option though (which is also the model we've been following), which is keep `fog` as the point of record, and bring things over to `fog-google` as needed.

`fog-google` will need changes made to run separately, and we will always need to be backwards compatible.

As a client, things should never change (unless a major version tweak).

Are there certain use cases where this migration strategy doesn't work for you?

**Comment by ihmccreery** [comment]
Okay, after discussing with @danbroudy, we've decided to freeze this codebase for now and put more effort toward stabilizing the Google codebase in `fog` before porting.

Initially, it was thought that the codebase was stable and that porting could happen; however, although while fog support for Google is currently functional, the tests do not give us an accurate picture of what's broken and what's not, (i.e. the mocks don't accurately represent the real service, so tests may be erroneously passing or failing; see fog/fog/#1266 and fog/fog/#1252, among others).  So, better to stabilize those tests, make sure that they accurately represent reality, then port over.

**Comment by icco** [comment]
Okee dokee. Note: if you wanted to rewrite the tests in a different test framework, you'd need to do that in `fog-google`. I always wanted to move to mini-test and some other mock framework, but never had the time, just because I found `fog`'s testing framework confusing.

**Comment by ihmccreery** [comment]
Ah! Good note, thanks.  We hadn't considered that limitation.

As far as I can tell, though, the `fog` codebase has started moving from `shindo` to `minitest` (e.g. fog/fog#2630 and [this commit](https://github.com/fog/fog/commit/18814bbefaf5915566270e11c674c45b3d938d5d).  `minitest` is now a development dependency, and is run on Travis.  It looks like the only tests to run on `minitest` are `bin` specs; I'm not sure how the crew over at `fog` would feel about us incorporating other (non-`bin`) tests into `minitest` *before* pulling out into a new gem.

@icco:

> Are there certain use cases where this migration strategy doesn't work for you?

Sorry I didn't respond to this clearly earlier.  I'm concerned about a few things.  Mostly, if we uncover a bug, (which we probably will,) while maintaining `fog-google`, we'll have two codebases in which we need to fix that bug.  And, if we change a bunch of things in `fog-google` before we port `fog` to use `fog-google`, that port is much less likely to be smooth, because there will be two moving parts: the port, and a bunch of code changes.  Thus the suggestion to either port-then-change or change-(in `fog`)-then-port.

Does that all make sense?

**Comment by plribeiro3000** [comment]
The migration is done. The gem should be g2g.

I've added several configurations like `coveralls`, `codeclimate` so it would be as smooth as possible for you guys. If one of them are not desired is easier to remove then add i guess. =)

Tests are passing and `minitest` is already setup to start migrating the tests. Travis will run both `shindo` and `ministest` for now.

Once you guys release the gem, don't forget to add @geemus, @tokengeek and @krames as owners on `rubygems`. After that let me know so i can remove the code from fog (or you can send a PR). =)

Feel free to ask anything you might want.

**Comment by geemus** [comment]
Thanks!

**Comment by ihmccreery** [comment]
Mad props, @plribeiro3000.  Thank you so much for your help.

**Comment by plribeiro3000** [comment]
@ihmccreery You are welcome! :+1:
