### ISSUE TITLE
Request For A New Release

### ISSUE THREAD

**Issue by seanmalloy** [fog/fog-google#309]
Now that #307 is merged to master would it be possible to get a release created and pushed to rubygems.org?

**Comment by erjohnso** [comment]
/cc @icco @emilymye 

Sean's done an amazing amount of work to update Vagrant to use the new and improved fog work.

**Comment by icco** [comment]
Totally, I thought I did this already, must have gotten distracted.

**Comment by icco** [comment]
This is done.

**Comment by erjohnso** [comment]
Thank you Nat!
