### ISSUE TITLE
Implement better examples

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#31]
Сurrently all fog-google examples are essentially code snippets:
Take https://github.com/fog/fog-google/blob/master/examples/image_all.rb as an example:

```
def test
  connection = Fog::Compute.new({ :provider => "Google" })

  # If this doesn't raise an exception, everything is good.
  connection.images.all
end
```

If someone wants to fix something quick, he needs to first set up a development environment, which potentially deters quick changes to the library and getting started easily.

What I propose is:
1) Briefly describe in the README to get `.fogrc` working, as in:

```
default:
    google_project: "my-awesome-project"
    google_client_email: "some-numbersandsuch@developer.gserviceaccount.com"
    google_json_key_location: "/tmp/gce-key.json"
```

2) Adding development dependencies to a separate group in Gemfile, for example, for latest git versions of fog and fog-core:

```
group :development do
   gem 'fog-core', git: "https://github.com/fog/fog-core"
   gem 'fog', git: "https://github.com/fog/fog"
   gem 'fog-google', path: "."
   gem 'fog-json'
end
```

3) With that set up we just need to add 4 lines to any example:

```
require 'bundler'
Bundler.require(:default, :development)
# Comment this if you don't want to make real requests to GCE
WebMock.disable!
```

And voila! It becomes an actual working script:

```
temikus λ cat image_all.rb
require 'bundler'
Bundler.require(:default, :development)
# Comment this if you don't want to make real requests to GCE
WebMock.disable!

def test
  connection = Fog::Compute.new({ :provider => "Google" })

  # If this doesn't raise an exception, everything is good.
  connection.images.all
end

images = test
pp test

temikus λ ruby image_all.rb >> log
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.5.
[  <Fog::Compute::Google::Image
    name="centos-6-v20131120",
    id="11748647391859510935",
    kind="compute#image",
    archive_size_bytes="269993565",
    creation_timestamp="2013-11-25T15:13:50.611-08:00",
    deprecated={"state"=>"DEPRECATED", "replacement"=>"https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-6-v20150226"},
    description="SCSI-enabled CentOS 6 built on 2013-11-20",
    disk_size_gb="10",
    self_link="https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-6-v20131120",
    source_type="RAW",
    status="READY",
    project="centos-cloud",
    raw_disk={"source"=>"", "containerType"=>"TAR"}
...
```

This is just a suggestion, but IMO this will save a bunch of time for anyone who is just starting to work on this library. If you don't want any changes in Gemfile/examples, then maybe just a change in the README/CONTRIBUTING?

Let me know what you think.

**Comment by ihmccreery** [comment]
Thanks, I think this is a great idea.  I'm [working on moving testing in this library from Shindo to Minitest, and implementing live acceptance tests in Minitest], but I think having easy-to-work-on examples are also key.  I also especially like having dependencies link to HEADs as opposed to current releases.

I probably won't have the bandwidth to take this on for some time, but if you want to take a crack at it, please do!

**Comment by icco** [comment]
It should be noted that the rakefile in the examples directory does something similar to this.

**Comment by Temikus** [comment]
@icco Yeah, I checked the rake task, but it breaks on the first file immidiately.
I'll go through examples and try to get them into shape, but do we need them all to be runnable via this task? If so, what to do with examples that require prior setup? (Like l7 load balancer one)

/CC @plribeiro3000

**Comment by plribeiro3000** [comment]
@Temikus I think that as the first step we could break the scenarios in different folders and create different tasks for each one so we can easily decide what to do next.
One task to run the ones that don´t need a setup and working keys and other for the _live_ ones.
What do you think?

**Comment by icco** [comment]
Originally the tests were written so each one was a single complete integration test. Running all of the commands to get the feature running.

**Comment by plribeiro3000** [comment]
@icco Got it. So this does not leave us much options i guess.
We need to work towards a better documentation to make easier for newcomers.

**Comment by Temikus** [comment]
Since integration tests and examples have somewhat different requirements, then I propose the following:
- [ ] Fix as many integration tests as possible.
- [ ] Copy all integration tests into `/tests/acceptance` or `/tests/smoke` and keep them there
- [ ] Test all examples and remove the non-functioning or no longer relevant examples
- [ ] Move complicated examples into /examples/case_studies

@plribeiro3000 @icco - Sounds good?

**Comment by icco** [comment]
My problem with `tests`, is that they don't run automatically and they don't work with mocks. I'd want to fix that first.

**Comment by Temikus** [comment]
This is obsolete, examples were updated but now we have a different issue - a ton of core examples are broken after 1.0 update :(

I'm slowly going through backlog of that.
