### ISSUE TITLE
`google_client_options` is documented in comment but seems to be ignored

### ISSUE THREAD

**Issue by ljfranklin** [fog/fog-google#313]
The constructor for `initialize_google_client` indicates that you can pass `google_client_options` which will be forwarded to the Google API Client. We wanted to set a timeout on the underlying API client, e.g. [read_timeout_sec](https://github.com/google/google-api-ruby-client/blob/b35f5face3649f25a4f24413b1fc9288f8bbe732/lib/google/apis/core/base_service.rb#L413). We were surprised to see that specifying `google_client_options.read_timeout_sec` had no effect on the timeout. Glancing at the code, the `google_client_options` is only described in a comment and that option is not used anywhere in the `shared.rb` file.

We were also confused that `initialize_google_client` returns a `ServiceAccountCredentials` object, not an actual client like [StorageService](https://github.com/fog/fog-google/blob/1b0132684bf10212591c5bf83205ad1f4b64bc3f/lib/fog/storage/google_json/real.rb#L17). Further it seems like the return value from `initialize_google_client` isn't really used, instead that method sets a global variable [Google::Apis::RequestOptions.default.authorization](https://github.com/fog/fog-google/blob/ee58e2a4d9502f2a4dc102ca6a4b664656551e3f/lib/fog/google/shared.rb#L119) to set default authorization for all the clients.

**Comment by icco** [comment]
Hmm, that's not good. What version of `fog-google` are you using? What services are you using?

**Comment by ljfranklin** [comment]
Using just the storage service for now, and the issue seems to exist on `master`.

**Comment by icco** [comment]
There's two storage services, how are you you initializing? Depending on which arguments you pass in we either use the old client or the new one.

**Comment by ljfranklin** [comment]
The Storage::GoogleJSON service: https://github.com/fog/fog-google/blob/ee58e2a4d9502f2a4dc102ca6a4b664656551e3f/lib/fog/storage/google_json/real.rb#L17

**Comment by evandbrown** [comment]
@Temikus Is this something you might be able to help with?

**Comment by Temikus** [comment]
@evandbrown Probably, will need some time though since this week is pretty busy. I'll try to take a pass at it on the weekend.

**Comment by Temikus** [comment]
So, from what I'm looking parameters for timeouts were added in https://github.com/fog/fog-google/commit/5f65487bb9f6b7d5038c7393ebc2a849b6257c05

@evandbrown can you help me define what else is missing here?

**Comment by Temikus** [comment]
This looks to be resolved so I'm going to close this issue out.
If I'm missing something, however - feel free to reopen! :)
