### ISSUE TITLE
google-api-client >= 0.20 support

### ISSUE THREAD

**Issue by DawidJanczak** [fog/fog-google#325]
Hello!

`google-api-client` 0.20.0 is out and it's required to work with Ruby 2.5 (https://github.com/google/google-api-ruby-client/pull/648) Would it be possible to bump the dependency for that lib in gemspec?

**Comment by Temikus** [comment]
@DawidJanczak I don't see why not, but it'll require some testing.

@icco - do you see any possible issues in bumping the spec a bit higher?

**Comment by icco** [comment]
Nope!

**Comment by DawidJanczak** [comment]
Thanks @Temikus !
