### ISSUE TITLE
unable to update the metadata instance on the cloud

### ISSUE THREAD

**Issue by zackyaz** [fog/fog-google#329]
Hi

use fog-google 1.3.3

i try to use the example https://github.com/fog/fog-google/blob/master/examples/metadata.rb

1) the :source_image => "debian-8-jessie-v20180329" need the full url
2) in the  server = connection.servers.create need to use attribute zone and not zone_name 

after create the instance i run the folowing
  server.metadata["test"] = "foo"
          server.metadata["test"] response with foo
  server.wait_for { ready? }
         server.metadata["test"] response nil

can you please let me know the command to apply the changes to the instance in the cloud

thanks zacky

**Comment by Temikus** [comment]
This is probably the same issue that I fixed for tags in #336
