### ISSUE TITLE
For some resources, resource#get(nil) returns a resource

### ISSUE THREAD

**Issue by ihmccreery** [fog/fog-google#33]
I would expect that, for example, `Fog::Compute[:google].servers.get(nil)` should either return `nil` or raise an error.  Instead, if at least one server exists in my project,

``` ruby
> Fog::Compute[:google].servers.get(nil)
=> <Fog::Compute::Google::Server
      name="server-name",
      ...
    >
```

This is because of the way we find servers, disks, and other resources that are zoned/regioned.  For example:

``` ruby
servers = service.list_aggregated_servers(:filter => "name eq .*#{identity}").body['items']
```

Every server matches that filter if `identity` is `nil`.

**Comment by Temikus** [comment]
Seems like this is now compounded by the new behavior of google-api-client.

```
@compute.get_image(project, nil)
=> #<Google::Apis::ComputeV1::Image:0x00007fa663dfc4b8
 @id=0,
 @kind="compute#imageList",
 @self_link="https://www.googleapis.com/compute/v1/projects/my-project/global/images/">
```
