### ISSUE TITLE
Expose `auto_delete` and `boot` as attributes

### ISSUE THREAD

**Issue by stiller-leser** [fog/fog-google#332]
Hi,

it would be nice if `auto_delete` and `boot` could be exposed as attributes. At least for `auto_delete` it would faciliate the cleanup very much. I agree that it is a bit more complicated for `boot` since I assume `disk.fist` is used to determine which disk is the boot disk?

Maybe I'll get some free time to look into it.

Thanks again,
stiller-leser

**Comment by stiller-leser** [comment]
Hi Temikus,

thanks for the active feedback - that's really awesome!

Indeed my request is regarding `Disk`, however I see your point. It indeed doesn't seem to be possible with the `REST-API`, I recently did some changes to the `kitchen-google` driver (see https://github.com/test-kitchen/kitchen-google/blob/master/lib/kitchen/driver/gce.rb#L451). Using the ruby gem, accessing `auto_delete` and `boot` are exposed.

Feel free to close this issue then.

**Comment by Temikus** [comment]
@stiller-leser Ah, I see. In this case it is possible since you’re setting them on instance creation. The problem here is that if we retrieve the disk on its’ own we cannot really get that subset of information.

Can I ask you for your use-case? (If you are able to tell, of course) I’m wondering if I can help you in another way, perhaps.

**Comment by stiller-leser** [comment]
@Temikus, 

No issue sharing my usecase here: I am basically spinning up instances for very short times on GCP and attaching some data disks to them of which snapshots are created (all using fog-google). The machines and data disks are then cleaned up. I have added the deletion of the data disks "manually" - having access to `auto_delete` was just me wanting to be extra lazy ;)

Thanks anyways, appreciate your active communication!

Cheers,
stiller-leser

**Comment by Temikus** [comment]
@stiller-leser You should be able to do it via `server.set_disk_auto_delete` method, you just need to call it from the server perspective after attaching the disk. Does that work?

Also - if you're running temporary workloads - take a look at `vagrant-google` which is based on this gem, it may be something that'll simplify your life.

**Comment by stiller-leser** [comment]
@Temikus 

Sorry for getting back to you that late. For now my integration works fine, so I'll close the ticket as it has enough information to be useful to others.
