### ISSUE TITLE
server.ssh yields "undefined local variable or method `public_ip_address'"

### ISSUE THREAD

**Issue by stiller-leser** [fog/fog-google#333]
When trying to ssh into a server using `server.ssh('ls /')` ```
*** NameError Exception: undefined local variable or method `public_ip_address' for #<Fog::Compute::Google::Server:0x007fe0a1e5d5d8>
Did you mean?  public_ip_addresses``` 
is returned. 

This is caused by https://github.com/fog/fog-core/blob/master/lib/fog/compute/models/server.rb#L53 in fog-core calling `public_ip_address` while fog-google only provides `public_ip_addresses` in https://github.com/fog/fog-google/blob/master/lib/fog/compute/google/models/server.rb#L203. Setting `server.ssh_ip_address = server.public_ip_addresses.first` solves the issue as a workaround.

Also as an additional FYI once `server.username` is set, the execution of ssh-commands works fine, however `:paranoid is deprecated, please use :verify_host_key. Supported values are exactly the same, only the name of the option has changed.` is shown.

**Comment by Temikus** [comment]
Thanks for submitting a bug!
I've just created a helper method, PTAL.

:paranoid was recently fixed: https://github.com/fog/fog-core/issues/226

**Comment by Temikus** [comment]
I assume this is fixed.

However, if I'm missing something - feel free to reopen!

Thanks again for submitting this @stiller-leser!
