### ISSUE TITLE
SQL is broken

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#337]
- SQL tests do not actually delete resources and are _extremely_ flaky due to the underlying API having issues from time to time combined with how instances are created for tests.

- Methods in sql model do not match other Fog models, nor do they match eachother:
```
        def clone(destination_name, async: true, log_filename: nil, log_position: nil)
        def destroy(async = false)
        def export(uri, options: {})
        def import(uri, options = {})
        def reset_ssl_config(async: true)
        def restart(async: true)
        def restore_backup(backup_run_id, async: true)
```
, notice the positional parameter in `import` and named one in `export`, positional in `destroy`, named in `restart` and `create` is missing sync/async logic altogether.

I'm going to rewrite the models and tests, but this will likely require a major version bump. 
@icco Are you ok bumping to 3.0 when I'm done? 

This should stabilize our CI tests so we can reliably verify changes and I'll bump to new google client to support Ruby 2.5 while we're at it.

**Comment by icco** [comment]
Sgtm :+1:

**Comment by Temikus** [comment]
What I've also noticed is that Fog::Google::SQL::User is not a classical Fog model, as it's tied to a particular instance.

I.e.:
  - Fog::Google::SQL.users.all() requires an instance
  - API doesn't provide a GET request for Users model: https://cloud.google.com/sql/docs/mysql/admin-api/v1beta4/users

I'm not sure we even need it, to be honest, as it's not particularly useful in its' current state.

**Comment by icco** [comment]
I'm down to just nuke it.
