### ISSUE TITLE
get and other business logic should be DRY-ed up in the models

### ISSUE THREAD

**Issue by ihmccreery** [fog/fog-google#35]
This issue is coming from the pain point that different resources behave differently when `#get('nonexistent-identity')` is called:
- for `Addresses#get`, `Servers#get`, and others, if the resource isn't found, it returns `nil`, (this seems to be the preferred behavior,) whereas
- for `UrlMaps#get`, `TargetHttpProxies#get`, and others, if the resource isn't found, it throws a `Fog::Errors::NotFound`.

This particular issue has been patched up in ihmccreery/fog-google@4e1d5dd36c2f8f174a126ed35a573fc971f1b954 and others, but it should be solved more permanently by DRY-ing up the duplicated business logic, (as well as implementing more consistent tests).

It's worth noting that these are _breaking changes_, but they are minor enough that I'm willing to put them in v0.1, though I'm happy to hear dissent.  It will require some serious workarounds to properly test, (per the work I've been doing moving to Minitest,) if we decide not to change the behavior until v1.

**Comment by icco** [comment]
This is kind of an extension of #33.

**Comment by Temikus** [comment]
This is no longer an issue and the behaviour is now codified in tests, so we have some safeguards against regression. Closing.
