### ISSUE TITLE
Issue with put_object_url and paths containing white spaces

### ISSUE THREAD

**Issue by miwelc** [fog/fog-google#357]
When creating signed urls with put_object_url and a path containing whitespaces the url translates whitespaces incorrectly.
Seems to be related to the issue described in https://github.com/fog/fog-google/pull/230.
I think 'host_path_query' is the one to blame, defined here: https://github.com/fog/fog-google/blob/20f3f5870a2b9d27f85685767a93cfc7abb69a5f/lib/fog/storage/google_json/utils.rb#L20-L28

**Comment by Temikus** [comment]
@miwelc Thanks for the issue! Can you give me a small repro by any chance?

That'll speed things up quite a bit since I'm less familiar with storage module, apologies m(_ _)m

**Comment by miwelc** [comment]
```ruby
storage = Fog::Storage.new({provider: 'google', google_storage_access_key_id: '', google_storage_secret_access_key: ''})
storage.put_object_url('bucket', 'just some file.csv', 2.minutes.from_now, {"Content-Type" => 'application/json'})
```

That snippet outputs urls with the following pattern: `https://storage.googleapis.com/bucket/just+some+file.csv?GoogleAccessId=&Signature=iIX3T0rUENag4bJuWDb7m3169sw%3D&Expires=1529313163`

Notice the '+' characters in the file name. It should be %20.

**Comment by Temikus** [comment]
@miwelc 
Thank you! I was able to repro with this:
```
storage = Fog::Storage.new({provider: 'google', google_storage_access_key_id: '', google_storage_secret_access_key: ''})

"https://storage.googleapis.com/bucket/just+some+file.json?GoogleAccessId=&Signature=ugbcdwxSsxHHf%2Fu%2F7LW4ApfjLVA%3D&Expires=1529368257"
```
This is google XML API though, not the new JSON one. The problem was actually related to #245 

I'm preparing a PR, plan to fix by EOW.

**Comment by Temikus** [comment]
@miwelc This is now fixed. Do you want me to roll out a version right away?

**Comment by miwelc** [comment]
Yes that would be greatly appreciated. :)

**Comment by Temikus** [comment]
@miwelc Released:
```
Pushed fog-google 1.6.0 to rubygems.org
```
