### ISSUE TITLE
Scope aliases consistency with gcloud

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#36]
We've had a discussion with @erjohnso about service account scopes inconsistency with official `gcloud` utility in https://github.com/mitchellh/vagrant-google/pull/71.

If one wants to define a service account scope using a short name, we have the following (left is `gcloud compute`, right is fog `scope:` attribute, since `gcloud compute` aliases do not match up to API endpoints:
```
          compute-ro         compute.readonly
          compute-rw         compute
          computeaccounts-ro computeaccounts.readonly
          computeaccounts-rw computeaccounts
          logging-write      logging.write
          sql                sqlservice
          sql-admin          sqlservice.admin
          storage-full       devstorage.full_control
          storage-ro         devstorage.read_only
          storage-rw         devstorage.read_write
```
Excerpt from `gcloud compute instances create --help`:
```
          Alias              URI
          bigquery           https://www.googleapis.com/auth/bigquery
          cloud-platform     https://www.googleapis.com/auth/cloud-platform
          compute-ro         https://www.googleapis.com/auth/compute.readonly
          compute-rw         https://www.googleapis.com/auth/compute
          computeaccounts-ro https://www.googleapis.com/auth/computeaccounts.readonly
          computeaccounts-rw https://www.googleapis.com/auth/computeaccounts
          datastore          https://www.googleapis.com/auth/datastore
          logging-write      https://www.googleapis.com/auth/logging.write
          monitoring         https://www.googleapis.com/auth/monitoring
          sql                https://www.googleapis.com/auth/sqlservice
          sql-admin          https://www.googleapis.com/auth/sqlservice.admin
          storage-full       https://www.googleapis.com/auth/devstorage.full_control
          storage-ro         https://www.googleapis.com/auth/devstorage.read_only
          storage-rw         https://www.googleapis.com/auth/devstorage.read_write
          taskqueue          https://www.googleapis.com/auth/taskqueue
          userinfo-email     https://www.googleapis.com/auth/userinfo.email
```

I was thinking about implementing it by either:
1) Keeping an additional mapping of those shortcuts and if one matches - expanding them (Since it's probably a bad idea to have only `gcloud`-style mappings available in scopes, as that may break things for existing users, who expect the old-style shortcut).
or
2) Creating a separate scope_aliases: attribute which will accept only aliased parameters in the same format as gcloud, expanding them and passing them on to service_accounts: later.

Any thoughts on this?

P.S. This has already been done in libcloud:
https://github.com/apache/libcloud/blob/trunk/libcloud/compute/drivers/gce.py#L971
https://github.com/apache/libcloud/blob/trunk/libcloud/compute/drivers/gce.py#L4677

**Comment by ihmccreery** [comment]
Hey Artem, this is a good write-up for this issue.  I think this should get fixed, and shouldn't be too difficult.  I recommend going with the first option; I think it'll be easier to maintain over time.

**Comment by Temikus** [comment]
For future reference, this quickly prints the list of all aliases:

gcloud compute instances create --help | sed -n -e '/Alias/,/^$/p' | sed 's/https:\/\/www.googleapis.com\/auth\///g'

**Comment by Temikus** [comment]
Long since implemented and live in #46

**Comment by darkn3rd** [comment]
@Temikus that command doesn't work anymore.

**Comment by Temikus** [comment]
@darkn3rd If you mean the gcloud command, yeah, they changed this from the previous layout so it's really not easy to parse anymore, e.g.:
```
gcloud compute instances create --help | grep 'aliases are' -A+62
```
I can mangle something more useable if required, the question is - what do you want to do? Maybe I can help you in another way.
