### ISSUE TITLE
Unable to add ssh-key when provisioning a new instance

### ISSUE THREAD

**Issue by EUGinsane** [fog/fog-google#362]
Hi all,
When new instance with:
```
 server = connection.servers.create(
    :name => "fog-smoke-test-#{Time.now.to_i}",
    :disks => [disk],
    :machine_type => "n1-standard-1",
    :private_key_path => File.expand_path("~/.ssh/id_rsa"),
    :public_key_path => File.expand_path("~/.ssh/id_rsa.pub"),
    :zone => "us-central1-f",
    :username => ENV["USER"],
    :tags => ["fog"],
    :service_accounts => { :scopes => %w(sql-admin bigquery https://www.googleapis.com/auth/compute) }
  )
```

I generated SSH key and new instance is suscess but I dont see any ssh key for VM instance. Please help me recheck. 

![Uploading ssh_key.PNG…]()
Thanks

**Comment by Temikus** [comment]
@EUGinsane Thank you for filing this!!! I found a regression, will fix it soon. 
Until then you can workaround by doing this after create:

```
server.add_ssh_key(ENV["USER"], File.expand_path("~/.ssh/id_rsa.pub"))
```

Apologies for the hassle m(_ _)m

**Comment by Temikus** [comment]
Fix has been pushed, this will be released with `1.6.0`

**Comment by EUGinsane** [comment]
Thanks @Temikus ,
I want to ask one question. When I created Windows instance, how to connection to this vm ?

**Comment by Temikus** [comment]
@EUGinsane This isn't implemented directly in fog, I'm afraid. 
There are 2 ways to connect - PowerShell and RDP[1]

If you go RDP route you can add an exec() in your script/app that will call the rdp client of choice.
Concerning powershell, I'm not sure.

[1] https://cloud.google.com/compute/docs/instances/connecting-to-instance
