### ISSUE TITLE
Fix examples

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#368]
Examples are in a bad state after 1.0 update. Some due to core functionality being broken, even.

We need to go through them 1 by 1 and decide whether to:
- Keep and fix example
- Keep and fix underlying logic
- Remove example

All examples should follow the default format of being runnable:
```
require 'bundler'
Bundler.require(:default, :development)
# Comment this if you don't want to make real requests to GCE
WebMock.disable!
```
(Not sure if WebMock is relevant anymore though, this needs checking.)

List:
```
λ find examples -print | while read example
do
  echo "- [ ] $example"
done
```
- [ ] examples/storage.rb
- [ ] examples/backend_services.rb
- [ ] examples/network.rb
- [ ] examples/l7_load_balance.rb
- [ ] examples/load-balance.rb
- [ ] examples/get_list_snapshots.rb
- [x] examples/create_instance.rb
- [ ] examples/pubsub/topics.rb
- [ ] examples/pubsub/subscriptions.rb
- [ ] examples/metadata.rb
- [ ] examples/monitoring/metric_descriptors.rb
- [ ] examples/monitoring/timeseries_collection.rb
- [ ] examples/monitoring/monitored_resource_descriptors.rb
- [ ] examples/storage_json.rb
- [ ] examples/get_list_images.rb
- [ ] examples/dns/project.rb
- [ ] examples/dns/zones.rb
- [ ] examples/image_create.rb
- [x] examples/bootstrap.rb
- [ ] examples/precreated_client.rb
- [ ] examples/sql/tiers.rb
- [ ] examples/sql/operations.rb
- [ ] examples/sql/ssl_certs.rb
- [ ] examples/sql/instances.rb
- [ ] examples/sql/flags.rb

**Comment by icco** [comment]
I'm going to try and go through these and test and validate some. Originally these were written to be integration tests, and very much are not. I'll see if we can duplicate them and also add comments to the examples folder.
