### ISSUE TITLE
Bootstrap method should look gcloud ssh keys

### ISSUE THREAD

**Issue by erjohnso** [fog/fog-google#37]
Currently, the live bootstrap test assumes the user has `~/.ssh/id_rsa[.pub]` for ssh keys. Google users will typically have `~/.ssh/google_compute_engine[.pub]`.  In that case, ssh will "Just Work"(tm), so the suggestion is for the live bootstrap test to first try to use a the google key, then could fall back to id_rsa.

wdyt @ihmccreery?

**Comment by erjohnso** [comment]
~/fog-google
erjohnso@fog-google$ rake test
Run options: --seed 56337

# Running:

...........................................E...

Finished in 550.471022s, 0.0854 runs/s, 0.2343 assertions/s.

  1) Error:
TestServers#test_bootstrap_ssh_destroy:
Errno::ENOENT: No such file or directory - /home/erjohnso/.ssh/id_rsa.pub
    /var/lib/gems/1.9.1/gems/fog-core-1.30.0/lib/fog/compute/models/server.rb:38:in `read'
    /var/lib/gems/1.9.1/gems/fog-core-1.30.0/lib/fog/compute/models/server.rb:38:in `public_key'
    /home/erjohnso/fog-google/lib/fog/google/models/compute/server.rb:224:in `save'
    /var/lib/gems/1.9.1/gems/fog-core-1.30.0/lib/fog/core/collection.rb:51:in `create'
    /home/erjohnso/fog-google/lib/fog/google/models/compute/servers.rb:72:in `bootstrap'
    /home/erjohnso/fog-google/test/integration/compute/test_servers.rb:14:in `test_bootstrap_ssh_destroy'

47 runs, 129 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/var/lib/gems/1.9.1/gems/rake-10.4.2/lib" "/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "te
st/**/test_*.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)

**Comment by ihmccreery** [comment]
It's actually not an issue with the test, but with the code in `Servers#bootstrap`: [lib/fog/google/models/compute/servers.rb#67](https://github.com/fog/fog-google/blob/master/lib/fog/google/models/compute/servers.rb#L67).

**Comment by Temikus** [comment]
Fixed in `1.0.0` and `.bootstrap` fixed in #367
