### ISSUE TITLE
Coverage integration into PR workflow

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#371]
Bringing out an item from #370 here, since this is pending Fog org action.

- [x] Add codecov bot or give `fog-google-bot` permissions to display coverage
- [x] Figure out automatic comments on PR's with coverage up/down
- [x] Make sure `master` branch has coverage

**Comment by Temikus** [comment]
@geemus @plribeiro3000 I’ve requested codecov.io integration for `fog-google` repo. Requires org approval apparently to add their bot account. 

If you think that’s too much - no worries, but I'll need someone with Owner permissions on `fog-google` to add the following here:
```
codecov:
  bot: fog-google-bot
```
, to the team YAML: https://codecov.io/account/gh/fog/yaml

We cannot use coveralls since they don’t support merged reports well and we need to do parallel testing (whole test suite takes almost 3 hours if we run sequentially).

Apologies for bothering you folks m(_ _)m

**Comment by geemus** [comment]
@Temikus I believe it should be approved now, just let me know if you need anything else. Thanks!

**Comment by plribeiro3000** [comment]
👍

**Comment by Temikus** [comment]
@geemus Thank you, Sir!

**Comment by Temikus** [comment]
Looks like the bot is starting to do its' magic: https://github.com/fog/fog-google/pull/373

I'll close this out once I'm sure everything's working (this particular PR doesn't have a base due to being submitted before the bot was approved)

**Comment by icco** [comment]
This seems to be working, closing!
