### ISSUE TITLE
Add 'label' field when create GCE disk

### ISSUE THREAD

**Issue by EUGinsane** [fog/fog-google#374]
Hi all,
Currently, I want create disk with 'labels' field when create a disk but I see fog-google no support this function. Please help me guideline implement this function.

https://cloud.google.com/compute/docs/labeling-resources

Thanks,

**Comment by Temikus** [comment]
@EUGinsane So labels already exist as a model attribute:

https://github.com/fog/fog-google/blob/23f3cf56c2cf06a3053b3760415cedf0361fc485/lib/fog/compute/google/models/server.rb#L69-L73

However, that means that you can only set labels on instance creation.

To set labels on running instances you'll have to add a `set_labels` method similar to `set_metadata` and add a `set_server_labels` request, similar to lib/fog/compute/google/requests/set_server_metadata.rb:

https://github.com/fog/fog-google/blob/23f3cf56c2cf06a3053b3760415cedf0361fc485/lib/fog/compute/google/requests/set_server_metadata.rb#L25-L30

**Comment by EUGinsane** [comment]
Thanks @Temikus ,
Currently, I can set labels for VM instance but I unable set labels for disks. I checked and I see fog-google only support set labels for instance and snapshot but not support for disks.

**Comment by Temikus** [comment]
@EUGinsane Ah, apologies, misread m(_ _)m

So, in this case, it may be enough to just create 2 attributes in the disk model: fog-google/lib/fog/compute/google/models/disk.rb

Then the advice for creating methods would be identical, just in the disk model.

Does this help?

**Comment by militarpancho** [comment]
#480 opened to achieve this enhancement

**Comment by militarpancho** [comment]
Hi! Is there any plan to release this change soon?

**Comment by Temikus** [comment]
@militarpancho I've been away for a bit so I need to see what state our trunk is in. I should have some time to tackle this next week.

**Comment by Temikus** [comment]
@militarpancho released: https://github.com/fog/fog-google/releases/tag/v1.10.0

Apologies for delays, this whole COVID situation threw a wrench in a lot of things.

**Comment by militarpancho** [comment]
Cool!, No problem, Thanks!
