### ISSUE TITLE
Do we need CodeClimate?

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#377]
I find it mostly provides the same suggestions as `Hound` does, but not as configurable so provides quite a bit of noise. It also provides test coverage but doesn't support distributed/parallel tests so not something we can use it for.

I'm in favor of removing it from the repo and leaving things people should focus on, like test coverage and docs.

@icco WDYT?

**Comment by icco** [comment]
I've found it pretty useless. Let's remove it.

**Comment by Temikus** [comment]
@icco Cool, I'll blast it.
