### ISSUE TITLE
Incorrect arguments for some operations.get calls causes exceptions

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-google#39]
The recent update to google/models/compute/target_pool.save and google/models/compute/forwarding_rule.save pass operations.get incorrect arguments which in turn throws an error when wait_for is called on a nil object. My colleague or I will be submitting a pull request soon to fix this

**Comment by plribeiro3000** [comment]
The original issue was reported by @ashmrtnz at fog/fog#3029.

cc/ @ashmrtnz @icco

**Comment by ihmccreery** [comment]
Thanks @ashmrtnz.  Let me know if you need any support on this.

**Comment by Temikus** [comment]
Since we don't have much context here I assume this has been fixed.

If I'm missing something, however - feel free to reopen!
