### ISSUE TITLE
Fog::Storage::GoogleXML::GetObjectHttpUrl#get_object_http_url is broken

### ISSUE THREAD

**Issue by yivo** [fog/fog-google#413]
Please, see the following: https://github.com/fog/fog-google/blob/master/lib/fog/storage/google_xml/requests/get_object_http_url.rb#L9 and https://github.com/fog/fog-google/blob/master/lib/fog/storage/google_xml/requests/get_object_http_url.rb#L14

It is probably something wrong. There are two calls: first https, the second is http which actually fails because url_options is not defined. I guess the first one should be replaced with the second one.

**Comment by Temikus** [comment]
@yivo This is my fault, missed it in review of #409 , #412 fixes it and I'll release a new patch release soon.

Apologies, we'll get this fixed up right away.

**Comment by yivo** [comment]
@Temikus Thank you!
