### ISSUE TITLE
The format Fog::Storage::Google is deprecated

### ISSUE THREAD

**Issue by HarlemSquirrel** [fog/fog-google#417]
Upon updating fog-core 2.1.2 (was 2.1.0), I received this warnings while running my test suite:

```
[fog][DEPRECATION] Unable to load Fog::Google::Compute
[fog][DEPRECATION] The format Fog::Compute::Google is deprecated
[fog][DEPRECATION] Unable to load Fog::Google::DNS
[fog][DEPRECATION] The format Fog::DNS::Google is deprecated
[fog][DEPRECATION] Unable to load Fog::Google::Storage
[fog][DEPRECATION] The format Fog::Storage::Google is deprecated
[fog][DEPRECATION] Unable to require fog/google/storage
[fog][DEPRECATION] The format fog/storage/google is deprecated
[fog][DEPRECATION] Unable to load Fog::Google::Storage
[fog][DEPRECATION] The format Fog::Storage::Google is deprecated
```

Adding `gem 'fog-core', '2.1.0'` to my Gemfile fixed this for me.

**Comment by Temikus** [comment]
Thanks for reporting this! I'll shortly release a version locking the dep and start working on sorting this out the proper way.

This is a good time to lock the rest of the fog core deps down as well.

**Comment by stanhu** [comment]
Thanks, the fog-core changes are really disruptive. The latest version of fog-aws uses fog-core 2.1.2+, and the warning messages are alarming if you go with the lowest common denominator and use fog-core 2.1.0 with fog-aws: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/21788#note_102836639

**Comment by Temikus** [comment]
1.8.0 has been released. 

If you're still seeing any issues - just let me know.

**Comment by stanhu** [comment]
@Temikus Thanks, first issue is that the fog-core version dependency wasn't bumped. :) https://github.com/fog/fog-google/pull/427

**Comment by codeodor** [comment]
> Adding gem 'fog-core', '2.1.0' to my Gemfile fixed this for me.

Is there a way to do that without getting all of the subcomponents?

**Comment by majksner** [comment]
I'm getting this warning again, using the latest version of fog-google. I can provide any additional info if necessary.

**Comment by Temikus** [comment]
@majksner this was an intentional tradeoff, see #562

**Comment by VILATTI** [comment]
+1
