### ISSUE TITLE
Error while creating VM on GCE

### ISSUE THREAD

**Issue by vincur96** [fog/fog-google#430]
I made a script to create a virtual machine in google compute engine:

`require "fog/google"

COMPUTE_ZONE = "us-central1-f"
MACHINE_TYPE = "f1-micro"

connection = Fog::Compute::Google.new

disk = connection.disks.create(
:name => "new-disk",
:size_gb => 10,
:zone_name => COMPUTE_ZONE,
:source_image => "debian-8-jessie-v20161020")

puts "Creating disk"

disk.wait_for { disk.ready? }

puts "Disk ready"

server = connection.servers.create(
:name => "new-server",
:zone_name => COMPUTE_ZONE,
:disks => [disk],
:machine_type => MACHINE_TYPE,
:private_key_path => File.expand_path("/.ssh/id_rsa"),
:public_key_path => File.expand_path("/.ssh/id_rsa.pub"),
:user => ENV["VinCur"])

puts "Creating server"

server.wait_for { server.ready? }

puts "Server ready"`

but it give me an error:
Traceback (most recent call last):
3: from vm.rb:6:in <main>' 2: from /Users/VinCur/.rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/fog-core-2.1.0/lib/fog/core/service.rb:98:innew'
1: from /Users/VinCur/.rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/fog-core-2.1.0/lib/fog/core/service.rb:268:in handle_settings' /Users/VinCur/.rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/fog-core-2.1.0/lib/fog/core/service.rb:244:invalidate_options': Missing required arguments: google_project (ArgumentError)

why?

**Comment by Temikus** [comment]
@vincur96 Sorry it took a while to respond, I've been away.

So, it says "Missing required arguments: google_project" That means that you haven't specified a google project when instantiating a service.

This should fix it:
```
connection = Fog::Compute::Google.new(google_project: my_project_name)
```
, alternatively you can create a `.fog` file with the credentials, as described in the readme here: https://github.com/fog/fog-google#credentials

Let me know if you still need any help!

**Comment by Temikus** [comment]
Since I haven't heard from you in a while I'll close this out. But feel free to reopen if this is still an issue!
