### ISSUE TITLE
 undefined method `self_link' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by vincur96** [fog/fog-google#431]
How can I solve it?

**Comment by Temikus** [comment]
@vincur96 - this is a generic error - I cannot day mich without context. It means that the object you’ve tried to call the self_link method on is nil.

Can you give me a code sample that triggers that or at least more detail on how you reproduced it with a traceback?

**Comment by vincur96** [comment]
Traceback (most recent call last):
	2: from vm.rb:8:in `<main>'
	1: from /Users/VinCur/.rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'
/Users/VinCur/.rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/fog-google-1.8.1/lib/fog/compute/google/models/disk.rb:44:in `save': undefined method `self_link' for nil:NilClass (NoMethodError)

**Comment by vincur96** [comment]
`disk = connection.disks.create(
    :name => "main-disk",
    :size_gb => 11,
    :zone_name => COMPUTE_ZONE,
    :source_image => "centos-7-v20181011")`

**Comment by Temikus** [comment]
@vincur96 I cannot reproduce this I'm afraid. Tried same version of ruby, `nil` as compute zone, etc.

What's the value of `COMPUTE_ZONE` in your case?

**Comment by Temikus** [comment]
Since I haven't heard from you in a while I'll close this out. But feel free to reopen if this is still an issue!
