### ISSUE TITLE
Need fix while generating metadata for ssh_keys

### ISSUE THREAD

**Issue by kgaikwad** [fog/fog-google#454]
[Line-557](https://github.com/fog/fog-google/blob/master/lib/fog/compute/google/models/server.rb#L557) generates metadata for ssh-keys.
The expect format of each ssh-key is `"[USERNAME_1]:ssh-rsa [EXISTING_KEY_VALUE_1] [USERNAME_1]"` mentioned in the [google document](https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys).

Here -> [Line-557](https://github.com/fog/fog-google/blob/master/lib/fog/compute/google/models/server.rb#L557) adds "[USERNAME_1]:ssh-rsa [EXISTING_KEY_VALUE_1]".  
Any specific reason that it is not appending `[USERNAME_1]` at the end of string? As user can pass comment while creating ssh-key itself but what if user wants to use same key. 

Using current code, I am facing error on VM edit from google console - 
'Invalid key. Required format: <protocol> <key-blob> <username@example.com> or <protocol> <key-blob> google-ssh {"userName":"<username@example.com>","expireOn":"<date>"}'

**Comment by icco** [comment]
weird that it fails, but there was no specific reason for leaving the comment out.

**Comment by kgaikwad** [comment]
@icco, 
Thank you for your responce. Yes, it creates VM without an error but later on edit from google console gives above error.

**Comment by Temikus** [comment]
@kgaikwad First of all - apologies for not getting back to you sooner. Don't currently have a lot of free time so this fell off my radar.

I think the issue is that your key is not in an expected format.

Standard pubkey generated by `ssh-keygen` should look like:
```
ssh-rsa AAAAVERYLONGKEYBODY== user@host
```

I've tried stripping the end off, e.g.:
```
ssh-rsa AAAAVERYLONGKEYBODY==
```
, and then I could reproduce the issue you were describing.

What command/lib are you using to generate the keys?

**Comment by ezr-ondrej** [comment]
@Temikus I believe the user@host is just an optional comment for the key and we should not expect it to be set as it is just a convention, but you can easily have the key left out.

Should we ensure the comment is present, if without it we fail?

Here is a key parser of gitlab: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ssh_public_key.rb#L26 which internally uses `net-ssh`( https://www.rubydoc.info/gems/net-ssh/2.9.4/Net/SSH/KeyFactory ) as a parser

Could we use this parser in similar fashion, to actually parse and validate the key?
