### ISSUE TITLE
SQLv1 Users test failing after Apr 21 2019

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#462]
```
TestSQLV1Users
  test_users                                                     ERROR (77.76s)
ArgumentError:         ArgumentError: host is required for this operation
            /tmp/build/7e99fb29/bundle/ruby/2.3.0/gems/fog-core-2.1.0/lib/fog/core/attributes.rb:155:in `requires'
            /tmp/build/7e99fb29/src/fog-google/lib/fog/google/models/sql/user.rb:19:in `destroy'
            /tmp/build/7e99fb29/src/fog-google/test/integration/sql/sqlv1/test_v1_users.rb:31:in `test_users'
```
Something seems to have changed API-side since there were no code changes and no major dep changes.

Problem is that the `host` parameter is now being recorded as `nil`, instead of (presumably) empty string:
```
pry(#<Fog::Google::SQL::User>)> self
=>   <Fog::Google::SQL::User
    name="fog-test-1-tests",
    etag="73ffe50dbfa75058461cfa409c3e3aec1fc9c3c67cxxxxx",
    host=nil,
    instance="fog-test-1-testsqlv1users-test-users-1559020503",
    kind="sql#user",
    project="my-project"
  >
```

@icco - any ideas on this one? Maybe I'm missing something?

**Comment by Temikus** [comment]
Seems like the API stopped returning the host field for users inserted without the "host" parameter when listing. I'm not sure whether this is WAI or not.

In the meantime I'll assign a default value to the model to mitigate.

Internal Google ref b/133808634

**Comment by icco** [comment]
That's real annoying. Thanks for chasing this down.

**Comment by icco** [comment]
This has been fixed on the google side as well.
