### ISSUE TITLE
Disk alreadyExists

### ISSUE THREAD

**Issue by majksner** [fog/fog-google#467]
Hi,

I'm getting error that disk already exists in case I want to start let's say 5 instances at the same time each of them with unique disk name.

This is the error I'm getting:
```
alreadyExists: The resource 'projects/*****/zones/europe-west1-d/disks/my-instance-DwYFAAMJDgw already exists
```
I'm using latest version of fog-google and Ruby 2.6.3

**Comment by Temikus** [comment]
Do you have a code snippet we can reproduce it with? Asking since I’m not entirely clear how this could be happening.

**Comment by majksner** [comment]
Unfortunately not, what is weird is that this happens randomly. I did happen last week for few hours and then it didn't happen again. I don't know if it's an issue with Google API but their status page never display issues or disruptions.

**Comment by Temikus** [comment]
Apologies for the late response m(_ _)m, not a lot of free time nowadays.

So I don't know of a behaviour where we would repeat calls in this manner. I think your best bet is to first try looking at the API logs on google side, e.g. going to the [log viewer](https://pantheon.corp.google.com/logs/viewer) and looking through the "compute.googleapis.com/activity_log" looking for the pd names. Maybe you have retry logic somewhere or a race condition?

**Comment by Temikus** [comment]
Since I haven't heard from you in a while I'll close this out. But feel free to reopen if this is still an issue!
