### ISSUE TITLE
Fog::Compute::Google::Network#gateway_ipv4 alias not working

### ISSUE THREAD

**Issue by djberg96** [fog/fog-google#478]
Ruby 2.5.7
fog-google 1.9.1

Seems like the `gateway_ipv4` alias for `gateway_i_pv4` isn't working:
```
require 'fog/google'
require 'fog/compute/google/models/network'

n = Fog::Compute::Google::Network.new
n.gateway_i_pv4 # nil, ok
n.gateway_ipv4  # boom, NoMethodError
```
Other aliases like `i_pv4_range` and `ipv4_range` seem to work, though.

**Comment by Temikus** [comment]
Hm, this is probably an issue with `google-api-client`, I'll investigate. Thanks for the report!

**Comment by djberg96** [comment]
@Temikus I think these are relevant:

https://github.com/googleapis/google-api-ruby-client/issues/666
https://github.com/googleapis/google-api-ruby-client/pull/669

**Comment by djberg96** [comment]
Still happening with fog-google 1.12.1 and google-api-ruby-client 9000.0.

**Comment by djberg96** [comment]
Still happening with fog-google 1.18.0

**Comment by djberg96** [comment]
@Temikus any update?

**Comment by djberg96** [comment]
Well, if you don't care, then neither do I.
