### ISSUE TITLE
Incorrect metadata format in comment

### ISSUE THREAD

**Issue by dvanbrug** [fog/fog-google#492]
I am having trouble setting the metadata for a server when I structure the metadata object according to documentation below:

https://github.com/fog/fog-google/blob/46d1bee9516bdbf3d020f012f7b7aee9039efd47/lib/fog/compute/google/requests/set_server_metadata.rb#L24

It seems like having a metadata object that includes an `items` key does not get parsed correctly.  However, setting the object to what the value of `items` was seems to work.  This also seems to be the way it is used in the test in:

https://github.com/fog/fog-google/blob/46d1bee9516bdbf3d020f012f7b7aee9039efd47/test/integration/compute/core_compute/test_servers.rb#L42

Or perhaps I am calling the method incorrectly?  It throws the following error when including the `items` key:

```
/Users/user/.vagrant.d/gems/2.4.9/gems/google-api-client-0.23.9/generated/google/apis/compute_v1/classes.rb:11437:in
`initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

**Comment by Temikus** [comment]
Hmm, I think the bug here is in the docs, not the test, as I seem to be the one responsible: https://github.com/fog/fog-google/commit/2554ba058c6634aaa7b739757f6f2392b2d710a4

**Comment by Temikus** [comment]
Fixed!
