### ISSUE TITLE
Connections stuck in CLOSE_WAIT

### ISSUE THREAD

**Issue by gabrielima** [fog/fog-google#526]
I have a lot of connections stuck in CLOSE_WAIT to the IP 142.250.218.208. 
After thorough investigation we concluded that it can only be the connections to GoogleStorage.
We're using Carrierwave 2.2.1 and fog-google 1.13.0.

Everytime I restart the server it clears the list of open connections, but in a few moments it starts to go up again.
Accumulating these connections leads to a crash of my application since it relies heavily on consuming third-party APIs. It's not them, we've checked.
Does anyone know what can be done in this case?

**Comment by Temikus** [comment]
We're kinda stuck without a repro environment at the moment so I'm not sure what I can help with here until we get back up and running. Is this still occurring?
