### ISSUE TITLE
Error: "Cannot insert legacy ACL for an object when uniform bucket-level access is enabled."

### ISSUE THREAD

**Issue by jywarren** [fog/fog-google#536]
`Google::Apis::ClientError`

`invalid: Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access`

https://sentry.io/share/issue/393f9e2786b543be9b2061a933268129/

**Comment by Temikus** [comment]
Is this a duplicate of #537 ?

**Comment by jywarren** [comment]
Yes, apologies, closing. I think my browser had a hiccup!
