### ISSUE TITLE
v0.0.6 source and tag

### ISSUE THREAD

**Issue by domcleal** [fog/fog-google#54]
rubygems.org has a 0.0.6 version published as of yesterday, but this repo doesn't seem to contain a tag or corresponding source code (lib/fog/google/version.rb says 0.0.5).

**Comment by ihmccreery** [comment]
Sorry, that was my bad; I released it and pushed to my repo, but didn't push upstream.  I just pushed it [here](https://github.com/fog/fog-google/releases/tag/v0.0.6).
