### ISSUE TITLE
1.16.0 doesn't support ruby 2.4

### ISSUE THREAD

**Issue by znep** [fog/fog-google#549]
It appears that https://github.com/fog/fog-google/commit/1e45ca170bda267143d4551ad120f70446e3d264 bumped dependencies to those that don't support ruby 2.4 any more.  eg.

```# /opt/sensu/embedded/bin/gem install google-apis-storage_v1 -v '~> 0.6'
ERROR:  Error installing google-apis-storage_v1:
	signet requires Ruby version >= 2.5.
```

The gemspec https://github.com/fog/fog-google/blob/master/fog-google.gemspec#L21 and readme https://github.com/fog/fog-google/blame/master/README.md#L11 still claim 2.4 support.

While continuing to support ruby 2.4 would be handy for us, I expect the best fix for you is updating the docs appropriately and also any CI tests running to match (didn't check to see what versions you are doing those against...)

**Comment by Temikus** [comment]
Thank you for reporting this. We generally support non-EOL ruby versions and make an effort to try and support one prior version as long as google deps don't make it difficult, hence why we're currently running CI with ruby-2.5+

I'll update the README and the gemspec. Sorry for any inconvenience caused :(
