### ISSUE TITLE
Uploads to Google Cloud are "not public" after Ruby upgrade

### ISSUE THREAD

**Issue by ReinierKorth** [fog/fog-google#554]
Hi,

I have upgraded Ruby to 2.7.4 and now all my uploads to Google Cloud are "not public" where they were always "Public to internet" before the upgrade.

Is there a way to fix this?

Thnx

**Comment by Temikus** [comment]
@ReinierKorth what's your use-case? You may have also changed to JSON API from XML (which uses public ACL by default).

If so, it's trivial to just add the ACL where it's needed:
    DIR.files.create(
      :key => new_filename,
      :predefined_acl => "publicRead"
    )

**Comment by ReinierKorth** [comment]
I have not changed anything. Just the versions of Ruby, Rails and the fog-google gem.

I have the following carrierwave initializer:

CarrierWave.configure do |config|
    config.fog_provider = 'fog/google'
    config.fog_credentials = {
      provider: 'Google',
      google_storage_access_key_id: ENV['GOOGLE_STORAGE_ACCESS_KEY'],
      google_storage_secret_access_key: ENV['GOOGLE_STORAGE_SECRET']
    }
    config.storage = :fog
    config.fog_public = true
    config.fog_directory = ENV['GOOGLE_STORAGE_FOLDER']
  end
