### ISSUE TITLE
Version 1.19.0 released to Rubygems but no tag in this repository

### ISSUE THREAD

**Issue by ekohl** [fog/fog-google#573]
https://rubygems.org/gems/fog-google/versions/1.19.0 exists but I don't see a tag for it, not even a commit in master. Was this an oversight?

**Comment by ekohl** [comment]
@geemus looks like you pushed 1.19.0 to Rubygems. Could you take a look?

**Comment by Temikus** [comment]
@ekohl I think @geemus didn't tag it, see: https://github.com/fog/fog-google/pull/571#issuecomment-1182704575

**Comment by Temikus** [comment]
@ekohl took a look inside - all content matches except for the version file. @geemus did you forget to push a branch?

**Comment by geemus** [comment]
Oops, I guess I must have forgotten or missed that somehow. Traveling presently, but will try to remedy this in the next few days once I'm home. Apologies for the confusion.

**Comment by ekohl** [comment]
Mistakes happen. Thanks for confirming!

**Comment by geemus** [comment]
Ok, home again. The v1.19.0 tag was indeed sitting on my home computer, just waiting for me. I've pushed it now, so hopefully we are all back on track. Apologies again for the confusion, I think I just was in a hurry, so I'll keep a closer eye next time around. 

Here is the tag: https://github.com/fog/fog-google/releases/tag/v1.19.0

Thanks!
