### ISSUE TITLE
HTTPS link

### ISSUE THREAD

**Issue by zggb** [fog/fog-google#58]
config.asset_host     = 'https://assets.example.com' 
doesn't work in CarrierWave.configure

How we can to show carrierwave use ssl versiton in url method?

**Comment by icco** [comment]
It should just work. What's the error you're seeing?

**Comment by zggb** [comment]
I created initializer fog.rb

    CarrierWave.configure do |config|
      config.fog_provider = 'fog/google'
      config.fog_credentials = {
        provider:                         'Google',
        google_storage_access_key_id:     ENV['GSASAK'],
        google_storage_secret_access_key: ENV['GSSAK']
      }
      config.fog_directory = 'persollo-bucket'
      config.asset_host     = 'https://assets.example.com'
      config.fog_public = false
    end

and use         
    <%= image_tag(@form.photo_url) if @form.photo_url.present? %>
in view

but url doesn't change 
and method .url return simple http too

**Comment by icco** [comment]
That sounds like a carrierwave bug... Fog's code for picking urls is https://github.com/fog/fog-google/blob/df9c0422bd846a97c3aafa6259843eebcf7dd6a1/lib/fog/google/models/storage/file.rb#L91

**Comment by zggb** [comment]
I was need to set 
    config.fog_public = true
Now it'w work fine.
