### ISSUE TITLE
multiple directories : one for each engine

### ISSUE THREAD

**Issue by webattitude** [fog/fog-google#59]
Hello, is it possible to have a different fog configuration for each engine mounted on the main application ?
typically I'd like each engine to upload to its own bucket.

**Comment by icco** [comment]
Are you referring to carrierwave?

**Comment by webattitude** [comment]
Hum yes I guess :$

**Comment by icco** [comment]
Looks like you found the right place: https://github.com/carrierwaveuploader/carrierwave/issues/1759

Good luck!

**Comment by webattitude** [comment]
I've a workaround thanks
