### ISSUE TITLE
Struggling to authenticate with service account (email & key)

### ISSUE THREAD

**Issue by micahalcorn** [fog/fog-google#60]
I keep getting `Missing required arguments: google_storage_access_key_id, google_storage_secret_access_key`. I understand that I am supposed to put my credential "in a /.fog" file, but I don't quite understand how that's supposed to work in the context of a Rails app. Can someone elaborate on how to configure this? I have tried passing the settings in an initializer (as suggested [here](https://github.com/fog/fog-core/blob/master/lib/fog/core/service.rb#L257-L270)), but they don't seem to get recognized in the [validate_options](https://github.com/fog/fog-core/blob/master/lib/fog/core/service.rb#L236-L253) method.

**config/initializers/fog.rb**
```Ruby
GoogleStorage = Fog::Storage.new(
  provider: 'Google',
  google_project: 'xxxxxxxxxxxxx',
  google_client_email: 'xxxxxxxxxxxxx-yyyyyyyyyyyyy@developer.gserviceaccount.com',
  google_key_location: 'private/google-cloud-service-key.p12'
)
```

**Comment by mlazarov** [comment]
use ```google_json_key_location:``` param.

**Comment by micahalcorn** [comment]
@mlazarov I can't use my `.pem` key? It is listed as an available option [here](https://github.com/fog/fog-google/blob/master/lib/fog/google.rb#L73).

**Comment by mlazarov** [comment]
I'm not sure for the .p12 key but with json file works perfectly.

**Comment by Temikus** [comment]
@micahalcorn, storage still uses the old authentication system, see https://github.com/fog/fog-google/issues/38

@mlazarov is talking about compute, which has a newer one.

**Comment by micahalcorn** [comment]
Thanks @Temikus. Sorry for the duplicate.

**Comment by joeyk16** [comment]
Hi @micahalcorn. I ran into your issue as well. Create the keys here https://bitmovin.zendesk.com/hc/en-us/articles/360001017393-How-can-I-create-Access-Secret-keys-for-Google-Cloud-Storage-

```
    config.paperclip_defaults = { 
      storage: :fog,
      fog_credentials: {
        provider: "Google",
        google_storage_access_key_id: ENV['GSTORAGE_ACCESS_KEY_ID'], #whenever see ENV and [], replaces with what's in your application.yml file
        google_storage_secret_access_key: ENV['GSTORAGE_SECRET_ACCESS_KEY']
      },
      fog_public: true,
      fog_host: ENV['GSTORAGE_HOST'],
      fog_directory: ENV['GSTORAGE_BUCKET'],
      path: ':class/:attachment/:id/:style/:filename' #:class is user/:attachment/:id is id of photo/:style is dimensiosn we spec'd/:filename
    }
```
