### ISSUE TITLE
Accessing Google compute instance groups

### ISSUE THREAD

**Issue by mlazarov** [fog/fog-google#61]
Is it possible to access google compute instance groups thought  fog-google?

**Comment by ihmccreery** [comment]
Unfortunately, no, that part of the API hasn't been built up for `fog-google`.  We'll happily take code contributions if you'd like to work on it.

**Comment by mlazarov** [comment]
Hi,
I'm trying to implement group instances for fog-google, but stuck on api call error:

```
/projects/fog-google/lib/fog/google/requests/compute/insert_instance_group.rb:15:in `insert_instance_group': undefined method `instanceGroups' for #<Google::APIClient::API:0x3fcd2a0c69d0 ID:compute:v1> (NoMethodError)
	from //projects/fog-google/lib/fog/google/models/compute/instance_group.rb:23:in `save'
	from /Library/Ruby/Gems/2.0.0/gems/fog-core-1.32.1/lib/fog/core/collection.rb:51:in `create'
	from r.rb:12:in `<main>'
```

Link to the API docs:
https://cloud.google.com/compute/docs/reference/latest/instanceGroups/insert
https://cloud.google.com/compute/docs/instance-groups/unmanaged-groups#create_unmanaged_group

You can see the model here:
https://github.com/mlazarov/fog-google/blob/1a34461181c5b8ba7fa6b0f9a9c5198deec41e50/lib/fog/google/requests/compute/insert_instance_group.rb

And all the source here:
https://github.com/mlazarov/fog-google/commit/1a34461181c5b8ba7fa6b0f9a9c5198deec41e50

Not sure what i'm doing wrong here

Martin

**Comment by icco** [comment]
Fixed with https://github.com/fog/fog-google/pull/62
