### ISSUE TITLE
Cut new Gem to adjust for Google DNS API v.1 deprecation

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#65]
v1beta1 will be deprecated very soon (docs state cutoff on Sept 25th)

We already had the support proposed in: https://github.com/fog/fog-google/pull/64
This needs to be acceptance tested but I don't quite know what's the current setup is.

Is master stable enough to start cutting out a new gem?
If not - what is needed to push this through?

/CC @ihmccreery who has access to Jenkins.

**Comment by erjohnso** [comment]
thanks for filing this @Temikus!

**Comment by Temikus** [comment]
Manually tested basic interaction with both recent op changes: https://github.com/fog/fog-google/pull/64 https://github.com/fog/fog-google/pull/56
Released the new gem under `0.0.9` tag to rubygems.
Re-checked with the released gem for good measure.

Thanks @erjohnso and @ihmccreery!
Closing this issue.
