### ISSUE TITLE
Drop travis support for deprecated Ruby versions

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#67]
As per @plribeiro3000 comment in: https://github.com/fog/fog-core/issues/162#issuecomment-143359520 we should drop support for the following ruby versions since fog 2.0.0 does not support it anymore:

`ruby 1.8.7`
`1.9.2` 
`ree`
`jruby-18mode`

**Comment by icco** [comment]
This is done as of https://github.com/fog/fog-google/pull/68.
