### ISSUE TITLE
project-private acl not allowed

### ISSUE THREAD

**Issue by gcolson** [fog/fog-google#71]
Hi,

It would be great to add the project-private predefined acl (https://cloud.google.com/storage/docs/access-control#predefined-project-private) to the list of valid acl here : https://github.com/fog/fog-google/blob/master/lib/fog/google/models/storage/directory.rb#L13

**Comment by icco** [comment]
Sure that's pretty straight forward.

**Comment by Temikus** [comment]
Fixed by #112
