### ISSUE TITLE
Clean up dependencies

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#74]
Example: `google-api-client` should be no longer needed as a dependency.

**Comment by plribeiro3000** [comment]
Isn't this a duplicate of #13 ?

**Comment by Temikus** [comment]
@plribeiro3000 OMG, sooooo sorry, I need a coffee or something.
This was intended for `vagrant-google`

**Comment by plribeiro3000** [comment]
ahhaha. No worries bro. I know the feeling when you have lots of stuff to do.
