### ISSUE TITLE
ArgumentError ( is not a recognized provider): on Heroku, using paperclip and fog

### ISSUE THREAD

**Issue by harishgeeth** [fog/fog-google#76]
<img width="1897" alt="screen shot 2015-10-13 at 4 15 27 pm" src="https://cloud.githubusercontent.com/assets/2483218/10468619/b3c57be2-71c5-11e5-9b70-c01af99e6929.png">

This works locally on dev machine, doesn't work on heroku though. Does anyone have any thoughts on this?

### User Model
```
has_attached_file   :avatar,
                      styles: {:big => "200x200>", thumb: "50x50>"},
                      storage: :fog,
                      fog_credentials: "#{Rails.root}/config/gce.yml",
                      fog_directory: "google-bucket-name"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
```

### Gemfile

```
gem "paperclip", git: "git://github.com/thoughtbot/paperclip.git"
gem 'fog'
```

**Comment by icco** [comment]
Usually asking the paperclip guys would be a better bet, since I don't know how they are parsing that into what they pass to fog, but you usually need a "provider" option in the credentials section. That error means that provider is `""` when it needs to be `"Google"`.

**Comment by icco** [comment]
Here are their docs: http://www.rubydoc.info/github/thoughtbot/paperclip/master/Paperclip/Storage/Fog

**Comment by harishgeeth** [comment]
That's a great tip though. Looks like now the problem is gone, I started passing direct hash into the fog_credentials, instead of "yml" file and it started working. Thank you for the pointer.
