### ISSUE TITLE
Possible async issue with Travis tests

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#85]
I noticed that travis test task never completes 100%, there's always a couple of tests pending, e.g.:
https://travis-ci.org/fog/fog-google/jobs/87321462
```
  6 pending, 227 succeeded in 0.834332688 seconds
```
And, I presume, if those do fail we never actually get notified.
I'll check it out and see if this can be synchronised.

/CC @plribeiro3000 @icco

**Comment by icco** [comment]
Iirc, this is for tests that don't have mocks. Also notice that all of the
tests in the test dir aren't running on Travis either.

**Comment by Temikus** [comment]
Yep indeed:
`tests/requests/compute/network_tests.rb`
```
pending if Fog.mocking?
```
Thanks for the explanation!
