### ISSUE TITLE
Rewrite save method to use `as` method from fog-core

### ISSUE THREAD

**Issue by icco** [fog/fog-google#86]
In https://github.com/fog/fog-google/pull/82/files#r42955444, @plribeiro3000 mentioned "I ended up adding a new feature to `fog-core`, the `as` option like [here](https://github.com/fog/fog-xenserver/blob/master/lib/fog/compute/xen_server/models/server.rb#L29). Then my `save` method is as simple as [this](https://github.com/fog/fog-xenserver/blob/master/lib/fog/compute/xen_server/models/instance_methods.rb#L22-L28) because the method `all_associations_and_attributes` will return a hash following the correct convention."

Let's change our save methods across the repo to use this if it makes sense.

**Comment by plribeiro3000** [comment]
:+1:

**Comment by plribeiro3000** [comment]
@icco @Temikus Let me know if you need help with this.

**Comment by icco** [comment]
@plribeiro3000 I know both @Temikus and I have been pretty swamped as of late, so if you have time, we'd appreciate any help.

**Comment by plribeiro3000** [comment]
@icco I was trying to take a stab at it and something came out. 

https://github.com/fog/fog-google/blob/4e3454e43bfc8a79fec7b9de4487a12173b93038/lib/fog/compute/google/models/backend_service.rb#L22-L30

In this code, it is sending only part of the attributes. The feature i mentioned can be used only for mapping of the attribute in `fog` back to the attribute `google` is expecting.

If we do need to cut down the attributes we need another way to do it, or perhaps a new feature at `fog-core`.

Maybe we can create a new method that accept an array and does return a hash with only those attributes mapped?

Does that make sense?

**Comment by icco** [comment]
@plribeiro3000 are you saying we can't use `as` because we aren't explicit about the attributes needed? Or something else? I'm not sure I 100% understand.

**Comment by plribeiro3000** [comment]
I'm sorry for the confusion. =s

We can use it to map the keys automatically like [here](https://github.com/icco/fog-google/blob/5c8f1f7e44ac711f7866ffe96324b87febe68223/lib/fog/compute/google/models/url_map.rb#L21-L27)

But as of now we only have `all_associations_and_attributes` which will return all attributes of the model mapped. And as it seems here, you only need to map and send part of the attributes.

Supporting partial mapping would be an improvement of the actual feature.

**Comment by icco** [comment]
Oh! I see what you're saying. Interestingly, I'm not sure what Google does if we send them extra attributes, we could also do the filtering at the request layer to make this work better...

**Comment by plribeiro3000** [comment]
My idea was to do filtering at the request layer. Do you think that it would worth the time to make the method accept an array of attributes to filter automatically?
