### ISSUE TITLE
Coveralls is not running

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#88]
COVERAGE env parameter was removed from travis recently: https://github.com/fog/fog-google/commit/0767fc4d653973689b3fcbc9d9acf6f5f5863195

Additionally, last build was somewhere in June:
https://coveralls.io/github/fog/fog-google

Do we need to fix our test coverage checks?

/CC @icco since he made the change and @plribeiro3000 for comments

**Comment by plribeiro3000** [comment]
I think we can add it back again. It might be that something is wrong thus it is not sending the data to `coveralls`.
Looking at the [docs](https://coveralls.zendesk.com/hc/en-us/articles/201769485-Ruby-Rails), it seems to be configured correctly.

**Comment by Temikus** [comment]
@plribeiro3000 Thanks! I'll sort this out.

**Comment by icco** [comment]
It wasn't working at the time, so was just saying every build failed. No
problems adding it back in if it works now.

/Nat

**Comment by Temikus** [comment]
Coveralls doesn't support parallel builds:
```
https://github.com/lemurheavy/coveralls-public/issues/613
```
I'll switch us to codecov.io, as per suggestions in the thread. That way we can merge results from parallel CI tasks into a single report. This is crucial since integration tests take a loooooong time if we don't run those in parallel (almost 2 hours).
