### ISSUE TITLE
Update CONTRIBUTORS.md

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-google#9]
We gotta keep up the [CONTRIBUTORS.md](https://github.com/fog/fog-google/blob/master/CONTRIBUTORS.md) file updated.

@geemus has a tool for that ([osrcry](https://github.com/geemus/osrcry)) but it does not help much here because we already have a ton of contributors from fog that does not have commit here and since the tool works on top of git, it will just drop all of them. What i'm doing so far is update it by hand but i guess that a provider of the size of this one can't keep it going like this.

Perhaps we might send some patches to @geemus. =)

**Comment by geemus** [comment]
hmm, that is tricky. I guess we could do a combined one of the other repo + this repo...

**Comment by plribeiro3000** [comment]
Do you think this can be done easily with `osrcry` or should we just create a link for it in the `README`?

**Comment by geemus** [comment]
hmm, osrcry can do it for a given repo, doing it for that + this would actually be inaccurate in the opposite way I suppose (over-reporting instead of under-reporting). I'm not sure how best to approach that, open to suggestions...

**Comment by plribeiro3000** [comment]
Perhaps we could have another file for it?
like `CONTRIBUTORS` and `PAST-CONTRIBUTORS` or something like that?

**Comment by geemus** [comment]
Maybe, yeah. I guess part of the trick is just figuring out the valid `PAST-CONTRIBUTORS` list. osrcry could certainly be updated to take the list in the file, add stuff from git log and then just keep the unique values. That would allow us to update it without clobbering old values, but we would still need to somehow get all the old values.

**Comment by plribeiro3000** [comment]
@geemus I was wondering. Maybe we can just have the `CONTRIBUTORS` point to the `CONTRIBUTORS` at `fog/fog`. Is that enough?

If so i can send you a PR for `osrcry` adding a config for this kind of stuff. What do you think?

**Comment by geemus** [comment]
Maybe? It's just weird in that there is some overlap that is hard to ascertain exactly. Probably as-is can be said to be good-enough?
