### ISSUE TITLE
`require': cannot load such file -- fog-google (LoadError)

### ISSUE THREAD

**Issue by ytyeoh** [fog/fog-google#98]
Hi, 
I am using fog-google v 0.1.1 with carrierwave to upload my file tu google. But got this error instead. It works with aws though.

Thanks

**Comment by Temikus** [comment]
Can you provide a repro example? What does your gemfile looks like?

Cheers,
A.

**Comment by ytyeoh** [comment]
GIT
  remote: git://github.com/carrierwaveuploader/carrierwave.git
  revision: cc2ab785a9d475a777f67f5fb12751c8c6171e03
  specs:
    carrierwave (0.10.0)
      activemodel (>= 4.0.0)
      activesupport (>= 4.0.0)
      json (>= 1.7)
      mime-types (>= 1.16)

GEM
  remote: https://rubygems.org/
  specs:
    abstract_type (0.0.7)
    actionmailer (4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.5)
      actionview (= 4.2.5)
      activesupport (= 4.2.5)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.5)
      activesupport (= 4.2.5)
      globalid (>= 0.3.0)
    activemodel (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
    activerecord (4.2.5)
      activemodel (= 4.2.5)
      activesupport (= 4.2.5)
      arel (~> 6.0)
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    adamantium (0.2.0)
      ice_nine (~> 0.11.0)
      memoizable (~> 0.4.0)
    addressable (2.4.0)
    arel (6.0.3)
    ast (2.2.0)
    astrolabe (1.3.1)
      parser (~> 2.2)
    autoprefixer-rails (6.3.1)
      execjs
      json
    axiom-types (0.1.1)
      descendants_tracker (~> 0.0.4)
      ice_nine (~> 0.11.0)
      thread_safe (~> 0.3, >= 0.3.1)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap (4.0.0.alpha3)
      autoprefixer-rails (>= 6.0.3)
      sass (>= 3.4.19)
    bootstrap-sass (3.3.6)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    bootstrap3-datetimepicker-rails (4.14.30)
      momentjs-rails (>= 2.8.1)
    braintree (2.57.0)
      builder (>= 2.0.0)
    brakeman (3.1.4)
      erubis (~> 2.6)
      fastercsv (~> 1.5)
      haml (>= 3.0, < 5.0)
      highline (>= 1.6.20, < 2.0)
      multi_json (~> 1.2)
      ruby2ruby (>= 2.1.1, < 2.3.0)
      ruby_parser (~> 3.7.0)
      safe_yaml (>= 1.0)
      sass (~> 3.0)
      slim (>= 1.3.6, < 4.0)
      terminal-table (~> 1.4)
    builder (3.2.2)
    bullet (5.0.0)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.9.0)
    byebug (8.2.1)
    capybara (2.6.0)
      addressable
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    clearance (1.12.1)
      bcrypt
      email_validator (~> 1.4)
      rails (>= 3.1)
    code_analyzer (0.4.5)
      sexp_processor
    codeclimate-engine-rb (0.1.0)
      virtus (~> 1.0)
    coderay (1.1.0)
    coercible (1.0.0)
      descendants_tracker (~> 0.0.1)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    colored (1.2)
    colorize (0.7.7)
    concord (0.1.5)
      adamantium (~> 0.2.0)
      equalizer (~> 0.0.9)
    concurrent-ruby (1.0.0)
    connection_pool (2.2.0)
    debug_inspector (0.0.2)
    descendants_tracker (0.0.4)
      thread_safe (~> 0.3, >= 0.3.1)
    diff-lcs (1.2.5)
    elasticsearch (1.0.15)
      elasticsearch-api (= 1.0.15)
      elasticsearch-transport (= 1.0.15)
    elasticsearch-api (1.0.15)
      multi_json
    elasticsearch-model (0.1.8)
      activesupport (> 3)
      elasticsearch (> 0.4)
      hashie
    elasticsearch-rails (0.1.8)
    elasticsearch-transport (1.0.15)
      faraday
      multi_json
    email_validator (1.6.0)
      activemodel
    equalizer (0.0.11)
    erubis (2.7.0)
    execjs (2.6.0)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    fastercsv (1.5.5)
    ffi (1.9.10)
    figaro (1.1.1)
      thor (~> 0.14)
    flay (2.6.1)
      ruby_parser (~> 3.0)
      sexp_processor (~> 4.0)
    flog (4.3.2)
      ruby_parser (~> 3.1, > 3.1.0)
      sexp_processor (~> 4.4)
    formatador (0.2.5)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    gon (5.1.2)
      actionpack (>= 2.3.0)
      json
      multi_json
      request_store (>= 1.0.5)
    guard (2.13.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, <= 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-puma (0.3.1)
      guard (~> 2.8)
      puma
    guard-rspec (4.6.4)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    haml (4.0.7)
      tilt
    hashie (3.4.3)
    highline (1.7.8)
    i18n (0.7.0)
    ice_nine (0.11.1)
    jbuilder (2.4.0)
      activesupport (>= 3.0.0, < 5.1)
      multi_json (~> 1.2)
    jquery-rails (4.1.0)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    jwt (1.5.2)
    listen (3.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.10)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    memoizable (0.4.2)
      thread_safe (~> 0.3, >= 0.3.1)
    method_source (0.8.2)
    mime-types (2.99)
    mini_portile2 (2.0.0)
    minitest (5.8.4)
    momentjs-rails (2.11.0)
      railties (>= 3.1)
    multi_json (1.11.2)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    nenv (0.2.0)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    notiffany (0.0.8)
      nenv (~> 0.1)
      shellany (~> 0.0)
    oauth2 (1.0.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    omniauth (1.3.1)
      hashie (>= 1.2, < 4)
      rack (>= 1.0, < 3)
    omniauth-facebook (3.0.0)
      omniauth-oauth2 (~> 1.2)
    omniauth-oauth2 (1.4.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    parser (2.2.3.0)
      ast (>= 1.1, < 3.0)
    pg (0.18.4)
    powerpack (0.1.1)
    private_attr (1.1.0)
    procto (0.0.2)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    puma (2.15.3)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.5)
      actionmailer (= 4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      activemodel (= 4.2.5)
      activerecord (= 4.2.5)
      activesupport (= 4.2.5)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.5)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    rails_best_practices (1.15.7)
      activesupport
      code_analyzer (>= 0.4.3)
      colored
      erubis
      i18n
      json
      require_all
      ruby-progressbar
    railties (4.2.5)
      actionpack (= 4.2.5)
      activesupport (= 4.2.5)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.0.0)
    rake (10.5.0)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    rdoc (4.2.1)
      json (~> 1.4)
    redis (3.2.2)
    reek (3.8.1)
      codeclimate-engine-rb (~> 0.1.0)
      parser (~> 2.2, >= 2.2.2.5)
      private_attr (~> 1.1)
      rainbow (~> 2.0)
      unparser (~> 0.2.2)
    request_store (1.3.0)
    require_all (1.3.3)
    rspec (3.4.0)
      rspec-core (~> 3.4.0)
      rspec-expectations (~> 3.4.0)
      rspec-mocks (~> 3.4.0)
    rspec-core (3.4.1)
      rspec-support (~> 3.4.0)
    rspec-expectations (3.4.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-mocks (3.4.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-rails (3.4.0)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.4.0)
      rspec-expectations (~> 3.4.0)
      rspec-mocks (~> 3.4.0)
      rspec-support (~> 3.4.0)
    rspec-support (3.4.1)
    rubocop (0.35.1)
      astrolabe (~> 1.3)
      parser (>= 2.2.3.0, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.7)
      tins (<= 1.6.0)
    ruby-progressbar (1.7.5)
    ruby2ruby (2.2.0)
      ruby_parser (~> 3.1)
      sexp_processor (~> 4.0)
    ruby_parser (3.7.3)
      sexp_processor (~> 4.1)
    rubycritic (2.6.0)
      colorize
      flay (= 2.6.1)
      flog (= 4.3.2)
      parser (>= 2.2.0, < 3.0)
      reek (= 3.8.1)
      virtus (~> 1.0)
    safe_yaml (1.0.4)
    sass (3.4.21)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    searchkick (1.1.2)
      activemodel
      elasticsearch (>= 1)
      hashie
    sexp_processor (4.6.1)
    shellany (0.0.1)
    shoulda-callback-matchers (1.1.3)
      activesupport (>= 3)
    shoulda-matchers (3.1.0)
      activesupport (>= 4.0.0)
    sidekiq (4.0.2)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      redis (~> 3.2, >= 3.2.1)
    slim (3.0.6)
      temple (~> 0.7.3)
      tilt (>= 1.3.3, < 2.1)
    slop (3.6.0)
    spring (1.6.2)
    sprockets (3.5.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.0.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    temple (0.7.6)
    terminal-table (1.5.2)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.2)
    tins (1.6.0)
    traceroute (0.5.0)
      rails (>= 3.0.0)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    uniform_notifier (1.9.0)
    unparser (0.2.4)
      abstract_type (~> 0.0.7)
      adamantium (~> 0.2.0)
      concord (~> 0.1.5)
      diff-lcs (~> 1.2.5)
      equalizer (~> 0.0.9)
      parser (~> 2.2.2)
      procto (~> 0.0.2)
    virtus (1.0.5)
      axiom-types (~> 0.1)
      coercible (~> 1.0)
      descendants_tracker (~> 0.0, >= 0.0.3)
      equalizer (~> 0.0, >= 0.0.9)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  bootstrap
  bootstrap-sass
  bootstrap3-datetimepicker-rails (~> 4.14.30)
  braintree
  brakeman
  bullet
  byebug
  capybara
  carrierwave!
  clearance
  coffee-rails (~> 4.1.0)
  colored
  elasticsearch-model
  elasticsearch-rails
  factory_girl_rails
  figaro
  gon (~> 5.1.2)
  guard
  guard-puma
  guard-rspec
  jbuilder (~> 2.0)
  jquery-rails
  mail
  momentjs-rails (>= 2.9.0)
  omniauth-facebook
  pg
  puma
  rails (= 4.2.5)
  rails_best_practices
  rspec
  rspec-rails
  rubocop
  rubycritic
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  searchkick
  shoulda-callback-matchers
  shoulda-matchers
  sidekiq
  spring
  traceroute
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

BUNDLED WITH
   1.11.2

**Comment by Temikus** [comment]
@ytyeoh I don't see `fog` or `fog-google` in your Gemfile, hence the load error.

You should add it, with something like (versions may differ in your use-case though):
```
  gem "fog-google", "~> 0.0.7"
  gem "google-api-client", "< 0.9", ">= 0.6.2"
```

However, if I'm reading something wrong or you're still having issues - feel free to reopen.
