### ISSUE TITLE
Implement SCRATCH disk type

### ISSUE THREAD

**Issue by benphelps** [fog/fog-google#99]
Is it possible to create a SCRATCH disk instead of PERSISTENT, I've looked through the source and it seems that PERSISTENT is hard coded into everything.

**Comment by icco** [comment]
https://cloud.google.com/compute/docs/disks/local-ssd

Scratch disks have been added since we last modified the disk API code. I personally don't have any plans to implement it, but pull requests are always welcome. An option at disk creation time makes a lot of sense.
